### ISSUE TITLE
Non-exhaustive case

### ISSUE THREAD

**Issue by apblack** [gracelang/language#1]
What should a non-exhaustive **case** statement mean?   Should a non-match raise an exception (and if so, which one), or should it be a no-op. like an **if** without an **else**?

**Comment by KimBruce** [comment]
I would prefer to see an exception raised if there is no match (NonExhaustiveMatch?) as it forces programmers to make sure there is a case for every possibility.  It is also easy to program around if you want the program to continue if there is no matching case.  Just add
```
   case{_ -> done}
```

Of course if you have a match as part of an expression (which is legal in Grace) then it is not clear what you would do with a non-exhaustive match -- you would have to return some sort of default value that presumably would blow up later.

```
var x := match(18) 
        case {17 -> 1}
        case {19 -> 2}
print(x)
```
What should be printed out when the above program is executed?  (See the minigrace answer at the end.)

I do think this is important to nail down.  (Even if you make the other choice.)

Minigrace answer to example:
FailedMatch(result = 18, bindings = [])

**Comment by kjx** [comment]
happy to throw!

**Comment by kjx** [comment]
Kernan does the right thing
```
>>> var x := valueOf {                                                      
...   match(18)                                                             
...     case {17->1}                                                        
...     case {19->2}                                                        
... }                                                                       
Uncaught exception:
RuntimeError: match-case fell through
    from «raise», at line 2904 of prelude
    from «fail», at line 294 of prelude
    from «match case case», at line 2 of source code
    from «apply», at line 1 of source code
    from «valueOf», at line 1 of source code
```
