### ISSUE TITLE
NaN and other floating-point constants are missing

### ISSUE THREAD

**Issue by apblack** [gracelang/language#10]
Should we define π, NaN and Infinity as constants?

It seems reasonable that we should, and  `π` and `infinity` seem like fine names for π and Infinity.  But NaN is a problem, because of the capitalization.  Using Grace conventions, should it be `nAN`?

I propose that we avoid this problem by not defining a constant for NaN.  It's not very useful anyway, and is likely to cause problems to novices, since NaN ≠ NaN.   

`infinity` in contrast, is quite useful, for example, as the initial value in a shortest path algorithm.

Note that the library does support the `.isNaN` method on Numbers.

**Comment by KimBruce** [comment]
Fine with me. However, someone should specify the properties of infinity.  I agree with no name for NaN.

**Comment by apblack** [comment]
> someone should specify the properties of infinity.

somebody has: the IEEE Standard for Floating-Point Arithmetic (IEEE 754).

I'm not an expert, but it seems that `infinity` > any number other than infinity, `- (- infinity) == infinity`, and anything other than 0 divided by 0 is `infinity`.  (0/0 == NaN).

**Comment by kjx** [comment]
> On 5/08/2015, at 5:32am, Andrew Black <notifications@github.com> wrote:
> 
> somebody has: the IEEE Standard for Floating-Point Arithmetic (IEEE 754).

again:  the big decision is, do we want to commit to IEEE FP for all numbers for ever?

**Comment by apblack** [comment]
>  the big decision is, do we want to commit to IEEE FP for all numbers for ever?

I don't think that we want to _exclude_ IEEE floating point from the language.  Nor do we want to exclude rationals forever.   But that's not this issue.   Open another one!

**Comment by apblack** [comment]
I believe that this issue is resolved.  The Number type has a method `isNaN -> Boolean` and the prelude defines constants `π` and `infinity`.  We need to put these in the spec.

**Comment by kjx** [comment]
sorry, but what is the status of this behaviour.  Do we want to ban it,  or should the spec be wide enough to permit it? 

```
>>> 0/0                                                                     
source code:1: P1020: Infix operator '/' must have spaces around it
>>> 0 / 0                                                                   
Uncaught exception:
ZeroDivisionError: R2012: Zero divided by zero is indeterminate.
```

**Comment by kjx** [comment]
added isNan to number & inifnti to maths module

**Comment by apblack** [comment]
infinity should just be a built-in constant, I think.  Most of what's in minigrace's math module should go away; it doesn't make OO sense to have a "math" object.  

In minigrace, π and inifinity are in the standard prelude.
