### ISSUE TITLE
Corrections to the Grammar

### ISSUE THREAD

**Issue by apblack** [gracelang/language#105]
How do we make corrections to the grammar that's in the spec?

Presumably, we should be correcting the source code and the tests, and then re-generating it.  But all of the parts are not in the repo.

I was looking at the grammar for blocks.  It reads:

> blockLiteral ::= lBrace ~ opt(ws) ~ opt(genericParams ~ opt(matchBinding) ~ blockParams ~ opt(ws)~ arrow) ~ innerCodeSequence ~ rBrace 
> genericParams ::= opt(lGeneric ~ rep1sep(identifier, comma) ~ rGeneric)
> blockParams ::= repsep( identifier ~ opt(colon ~ typeExpression), comma) 

Apart from using the name _genericParams_ in place of _typeParameters_, this doesn't look right.  It says that if a block has _typeParameters_, then it must have _blockParams_.

I think that a _matchBinding_ is just a special case of a _blockParam_, and should not be an alternative production.  

```
{ "a" -> ... }  \\ is a shorthand for
{_:"a" -> ... }
```

**Comment by kjx** [comment]
> How do we make corrections to the grammar that's in the spec? 
> Presumably, we should be correcting the source code and the tests, and then re-generating it. 

sure. hopefully coordinating with me, (although perhaps github will do this for me) 

> But all of the parts are not in the repo.

I've just pushed and pulled, then do ". runtest.sh" and "runall" and all the tests run on the latest Kernan.

**Comment by kjx** [comment]
We agreed to replace it with the Smallgrace grammar - see #131
