### ISSUE TITLE
Garbled section in spec.md

### ISSUE THREAD

**Issue by pmmccorm** [gracelang/language#106]
It appears that the default-methods section is garbled or not rendering correctly, see:

https://github.com/gracelang/language/blob/master/spec.md#default-methods

**Comment by kjx** [comment]
Hmm, according to the logs this was a change by @apblack -- not sure why though?

**Comment by apblack** [comment]
How aer you rendering the makerdown?  The pdf and html produced by pandoc look fine.  You should be aware that Github doesn't implement everything that pandoc does.  In particular, github-flavoured markdown doesn't seem to provide a way to do multi-line tables, which is what is needed here.  Look, for example, at http://web.cecs.pdx.edu/~black/OOP/GraceResources/spec.html#default-methods and http://web.cecs.pdx.edu/~black/OOP/GraceResources/spec.pdf

I think that the commit message explains why I made the changes.

If I'm wrong, and you can find multi-line table markdown that works for github as well as pandoc, then by all means go ahead and edit it.

**Comment by apblack** [comment]
On a related topic, if we want to host the spec on github, then we should look at using Jekyll as a site generator.  I'm told that github will run the Jekyll scripts automatically on checkin, and generate the pages: https://help.github.com/articles/about-github-pages-and-jekyll/

Jekyll used "[kramdown](http://kramdown.gettalong.org/syntax.html)" flavoured markdown, which does not appear to support multi-line tables.
It does let one put raw html into a markdown file, though.  Does pandoc allow raw html in a markdown file, and generate correct LaTeX from it?

**Comment by kjx** [comment]
> Jekyll used "kramdown" flavoured markdown, which does not appear to support multi-line tables.

well let's not do multi-line tables then.   I seem to remember tweaking the previous version so it looked OK on pandoc latex, pandoc html, and github.

> Does pandoc allow raw html in a markdown file, and generate correct LaTeX from it?

probably. but I think we shouldn't do that unless we really, really, really need to 
(where "unless we really, really, really need to" means "--- we don't need to")

**Comment by apblack** [comment]
I don't see a problem with using pandoc markdown that github doesn't support.  In particular, we use  $-escapes in our markdown, since both latex and html formatted versions support them, eveb though github doesn't.

We are looking at Jekyll as a way of getting github to host documentation.  Until then, I'm going to close this issue, since it has nothing to do with Grace or its libraries.
