### ISSUE TITLE
type arguments to classes and methods

### ISSUE THREAD

**Issue by KimBruce** [gracelang/language#107]
Now that we've changed the syntax for type arguments, is there any reason to block generic parameters from being alone in a method part.  E.g., why shouldn't the following be a legal class header?
```
class matrix [[T]] size (rows: Number,cols: Number) defaultValue (dvalue:T) -> 
                     Matrix[[T]]
```
Currently minigrace gives an error message:
Syntax error: a class must have a '{' after the method header.

**Comment by kjx** [comment]
Because type arguments are usually optional?  Different parts of method names currently have to be separated by delimited arguments. 

Or are you proposing to make such type arguments mandatory?

**Comment by KimBruce** [comment]
That's a good point.  It is just much nicer looking to put the type parameters before a method part with parameters.
