### ISSUE TITLE
Types Issues needing resolution

### ISSUE THREAD

**Issue by apblack** [gracelang/language#123]
For our meeting week, let's talk about some of the open issues about types.  The relevant issues seem to be:
- Singletons and Types #100
- Types are *not* manifest #101
- Non-existant reference in Spec #122
- Interface of singleton(o) types #81
- What's a type (module "build order") #64
- Type enquiries #92

It would be great if we could all read the above issues remind ourselves of what we used to think before we meet!

**Comment by KimBruce** [comment]
That’s fine with me.  However, I’ll have to duck out after about an hour as I have to go to a talk by a job candidate.

Kim

**Comment by apblack** [comment]
The only issues on the above list not now closed are #64 and #101.

**Comment by apblack** [comment]
I have just closed issues #64 and #101.  So we are done with this one too!
