### ISSUE TITLE
Use internal iterator `do(_)` method for maybe objects 

### ISSUE THREAD

**Issue by apblack** [gracelang/language#14]
There was an interesting talk at SNAPL about treating all variables as collections — trivial collections that are either empty, or contain a single element.

This gives a facility like the ability of Javascript or Ruby to ask whether or not a variable is defined, but by re-using the same syntax as for iterating over a collection.

So, if `v` is possibly undefined, and you want to request `doit` on `v`, you might write:

```
v.do { just -> just.doit }
```

This can be statically typed, and in my view is an improvement over the idiom used in the compiler:

```
if (false ≠ v) then { v.doit }
```

**Comment by kjx** [comment]
That idiom is evil. Can we close this?

**Comment by apblack** [comment]
> That idiom is evil. Can we close this?

Which idiom?  The `false` idiom, or the use of `Maybe` objects?

**Comment by kjx** [comment]
the 'false' idiom is evil. (although on reflection I'm less sure why that I was before).

Using "do" may be monadic, but it seems like a shorthand for the "elvis" operators in contemporary scripting languages (although I guess we have sh to blame for them). 

The point of having an undefined value we **cannot** observe is that we cannot observe it,
with the idea that constructors etc would make things defined --- part of me still likes the idea of 
the "bottommost" constructor throwing an exception if there are still undefined variables left by then -
(object is uncooked after construction).   But perhaps that's too strict for a dynamic language? 

We could have (or one could make) a "missing" value with this behaviour: name inspired by SQL, rather than "null"; and with medium-strength reflection it could even have empty implementations for all the methods in its type)..

So: my take is: the false idiom is evil; the maybe/missing/null/elvis idiom is OK but shouldn't be the default.      Perhaps we need another tag to mean "don't forget this proposal but not a priority for the next version of the spec?"

**Comment by KimBruce** [comment]
I also hate the "false" idiom.  It drove me crazy when I saw it.  I agree with putting it all on the back burner.

**Comment by apblack** [comment]
The major use case for testing for undefined is covered by _once methods_ #41.  This issue is about the protocol for _maybe_ objects, which I though that both of you liked!

**Comment by kjx** [comment]
> This issue is about the protocol for maybe objects,

Is it, umm OK.  What's the proposal?  That every object understands **do**?   
Is **do** now a synonym for **apply(_)**?

**Comment by apblack** [comment]
The proposal is that Maybe objects understand do(_).   

I don't think that Maybes are very OO — I think that application-sepcific null objects are usually cleaner.  I  don't know what th protocol of Grace's Maybes would be.  (Haskel's is described [here](https://hackage.haskell.org/package/base-4.8.2.0/docs/Data-Maybe.html)).

If you want to give up on Maybes, then I will quickly agree, and we can close this issue.  But if you want to keep them, then I think that making them understand the `do` protocol is much cleaner than forcing the programmer to use case.  

If you adopt the Haskel interface for Maybes, then `maybeObj.do { ... }` can be simulated by `maybeObj.maybeToList.do { ... }`.  Making the maybe object understand `do` directly is clearer _and_ more efficient.

**Comment by kjx** [comment]
OK, so let me try to work this out:

instead of 
```
var v : Boolean | Doit = false
...
if {random} then { v := anObjectThatUnderstandsDoit } 
...
if (false != v) then { v.doit }   // probably won't type check btw! 
```

and _as well as_ 

```
var v : Boolean | Doit = false
...
if {random} then { v := anObjectThatUnderstandsDoit } 
...
match (v)
    case { v1 : Doit -> v1.doit } 
```

we would support something  more like:

```
def v = maybe[[Doit]] 
...
if {random} then { v.value:= anObjectThatUnderstandsDoit } 
...
v.do { v1 : Doit -> v1.doit } 
```

**Comment by apblack** [comment]
In your final example, I'm guessing that you would say

    var v: Maybe[[Something]]
    ...
    if { random } then { v := just(anObjectThatUnderstandsDoit } else { nothing }
    ...
    v.do { v1 -> v1.doIt }

although I do really like calling the λ-bound variable `just` :-)   The idea is that `just(_)` and `nothing` are two classes that make different implementations of the Maybe type.

**Comment by kjx** [comment]
> In your final example, I'm guessing that you would say

Hah!  No, I think I meant to say (or write) what I said (or wrote).  Your example is more typical of the idioms from the functional community (apart from assigning to the variable).  I just made up mine,  assuming a _maybe_ object that starts uninitialised (i.e. your nothing) but on being assigned (**value:=**) gets that value:

```
type Maybe[[T]] = interface {
  request value:=(_:T) -> Done 
  request value -> T 
  request do ( _ : interface { apply<R>(_: T) -> R } ) -> R 
} 
```

Either way: is this a library issue now, and so should be low priority?

**Comment by apblack** [comment]
Yes, it's a library issue.  I just changed the tag.  Someone should build a maybe module.

Is there a benefit to the extra level of indirection in your proposal _vs_ mine?

**Comment by KimBruce** [comment]
I agree with putting this issue off for now, though we will certainly need to introduce a Maybe type operator to make life easier for programmers (even though I’d often rather they define their own Null-like object and use a variant type).

However, I recently realized (via writing lots of Haskell programs involving lists), that using [[T]] for type parameters is ambiguous, as that also indicates a list whose only element is a list containing T.  Perhaps context will always make it clear, but I doubt it.  Let’s instead go with [|T|] (though that is tricky to type) or something else that will be unambiguous.

Kim

**Comment by kjx** [comment]
Kim - operator syntax is also in #18.    We can use spaces to disambiguate [ [ from [[, just as we use spaces to disambituate "a a" from "aa".

**Comment by kjx** [comment]
> Is there a benefit to the extra level of indirection in your proposal vs mine?

there isn't an extra level of indirection between your's & mine.  You go mutable var then immutable objects, I go immutable def then a mutable object.  Kim, using ` A | B` types, is the one without the level of indirection, with just one mutable var.

**Comment by apblack** [comment]
Grace has had an _option_ module since commit a86012981 (March 2016).  Some students asked for it, and it seems harmless.  It required no language changes.  (A short survey showed that _option_ was more-frequently-used as a name than _maybe_, notably in Scala and ML).  The type `Option` is defined as follows:
```
type Option⟦T⟧ = type {
    value -> T
    do(action:Block1⟦T, Done⟧) -> Done
    isSome -> Boolean
    isNone -> Boolean
}
```
There are two constructors: `some⟦T⟧(contents:T) -> Option` and `none⟦T⟧ -> Option`.  Requesting `value` on an `Option` created with `none` is a `ProgrammingError`.

At present, `Option` does not support the full collection interface, which is what Scala advocates.
