### ISSUE TITLE
`outer` is not well-defined 

### ISSUE THREAD

**Issue by apblack** [gracelang/language#15]
A while back we decided that `outer` should be like `super`: that it can be used only before `.`, and  that it should search as many levels back in the lexical chain as necessary to find the referenced attribute.  

I believe that this is wrong.  Unlike `super`, `outer` actually refers to a real object.  It is quite reasonable to want to pas it an argument, not just make requests on it.

I can see a number of ways of fixing this.

1.  make `outer` mean the object enclosing `self`, `outer.outer` mean the object enclosing that, and so on.  This is potentially confusing with constructs like `class`, that introduce two levels of implicit `object`, and even with `factory method`, which introduces one.

2.  eliminate `outer`, and require the programmer to name the target object, by inserting a `def myName = self` inside it somewhere.   (This is what I have been doing, since outer is broken in _minigrace_).

3.  change the syntax to allow the programmer to insert a local name between the keyword `object` and the opening `{`.  The scope of this name would be from the opening `{` to the matching closing `}`.  This essentially makes the convention of (2) above into part of the syntax.

Perhaps there are other options that I haven't thought of.

**Comment by kjx** [comment]
outer went back to meaning the immediate enclosing object.
