### ISSUE TITLE
can traits contain statefull classes?

### ISSUE THREAD

**Issue by kjx** [gracelang/language#150]
(this might just be a question of wording - but perhaps it is a deep design question).

Is this legal?

```
trait partOne {
   class one {
       var x is public := 3
   }
}
```

The spec says _"a trait object is created by an object constructor that contains no field declarations and no executable code"_.    Does this mean **directly contains** no field declarations at the top level, or **transitively contains** no field declarations inside it?

Similarly I guess "executable code" means no *initialisation* code at the top level - but...?

**Comment by apblack** [comment]
Yes, this is OK.  In fact, your example illustrates @kjx's encoding of dialects.  

The Spec means "directly contains".  We should reword.

**Comment by apblack** [comment]
I've reworded this in commit cb69601.
