### ISSUE TITLE
methods of graceObject

### ISSUE THREAD

**Issue by apblack** [gracelang/language#155]
In the spec it says that any object not inheriting from anything else inherits from graceObject, and that graceObject defines the following methods:

|  Method                            |    Return value                                           |
| :-----------------------------------------------  | :------------------------------------------- |
| `isMe (other:Object) → Boolean`; _confidential_  |    true if other is the same object as self |
| ≠ `(other:Object) → Boolean`|    the inverse of ==                                 |
| `asString → String`               |    a string describing self                          |
| `asDebugString → String`          |    a string describing the internals of self         |
| `:: (other:Object) → Binding`     |  a Binding object with `self` as key and `other` as value|

The method `≠` was put there (by me) as a placeholder, until I had implemented traits; once we have a trait `identityEquaility ` defined by something like
```
method identityEquaility {
    def hashCache = random.integerBetween 0 and maxHash
    object {
        method == (other) { isMe(other) }
        method ≠(other) { (self == other).not }
        method hash { hashCache }
    }
}
```
there is no reason to put `≠` in `graceObject`.

I've also realized that, since `==` is no longer in `graceObject`, `::` should not be in `graceObject`either: if you can't test an object for equality, you can't use it as a key in a dictionary, which is the motivation for `::`.  So we should move `::` to traits `identityEquaility` and `abstractEquality`(the latter being a trait that requires the user to define `==` and `hash` and provides `≠` and `::`).

Much as I really liked the conclusion in _The Left hand of Equals_ essay — that we should have a _confidential_ `isMe` method in every object, which the object can choose to expose if it so wishes — we don't really need `isMe` either.  This is because we also admitted in that essay that we needed an identity-testing method in `mirror`, and once we have that, the `identityEquality` trait can define
```
    method = (other) { mirror.isIdential (self, other) }
```
and the user of the `identityEquality` trait won't see any difference.

This leaves `graceObject` with just the two stringification methods `asString` and `asDebugString`.  In practice, I really like having those methods be available by default, and I've taken some pains in _minigrace_ to try to make the default implementations be useful.  So, for example, 
```
def horrible = object { }
print(horrible)
```
prints "a horrible", not "an object".
But the fact remains that the type `Object` is now the same as the type `Done`, which doesn't feel right.  `Object` and `Done` still have different pragmatics: one is intended to be the supertype of all other types, while the other is intended to be the return type of an operation (such as an assignment) that has no result.  Our type system doesn't reflect this difference, though.

To some extent we can sidestep this issue by saying that `graceObject` (the superobject off all objects) is defined by the current dialect, and thus is _not_ part of the core language, whereas `Done` _is_ defined by the core language, because it characterizes the object returned by an assignment (which I think has to be defined in core Grace).  If we do that, though, we need a way of defining `graceObject` in a dialect that does not require `graceObject` to be already defined.  I've thought of using
```
    inherit none
```
for this, but then we have to ask: where is `none` defined?  And so on.

@kjx has argued that we should be "pure" and get rid of `graceObject` altogether, so that type Object would be empty and there would be no default inheritance.  I've argued against that because of the enormous practical advantages of having every object support `asString` and `asDebugString`.

Like most issues in OO, the real concern here is not _whether_ we have default code to stringify any object — we need that regardless, because user-written asDebugString methods can fail — but where to put it.

**Comment by kjx** [comment]
So, the thing is, once you've got rid of everything in `graceObject` except `asString` and `debugString`  we should think hard about whether they should stay there too. 

> `print(horrible` prints "a horrible", not "an object". 

How does it do that?  Seems to me saying that print does not _depend_ on `asString` or `debugString` - and then does magic - is better than adding complexity to the inheritance mechanism to inherit that magical implementation.  There's nothing wrong with `print` or anything else testing to see whether than object supports either of these requests, but that doesn't mean that 

> the real concern here is not whether we have default code to stringify any object — we need that regardless, because user-written asDebugString methods can fail — but where to put it.

right - and the complexity costs different choices impose on the rest of the language. 

Printing/stringification, I think, we can handle in various ways.  Equality seems more important to me.   Ideally we would look through @KimBruce's book (or other curricula) to answer questions like: How important is default (identity) equality early on?       One people start needing equality, how bad is it to have to `use equalityTrait` on every object that's going to be looked up in a collection.  Once people start defining it, how bad is it to have to `use identityEquality`.

**Comment by kjx** [comment]
see also #153, #49...

**Comment by kjx** [comment]
'''
inherit none
'''

None could be defined by magic. It could even (almost) be `done`  - but see comments on #152

**Comment by kjx** [comment]
I tried looking through Kim's book - as far as I can see, == etc are only used on primitives or library objects,
graceObject is mentioned on p421, key descriptions are on 431-434, and 438. Pretty much *every* example
of a comparison - even after that - seems to be on primitives or library objects.
There are only 4 occurrences of "method ==" in the book --- and very worryingly,  no mentions of overriding hash when overriding equals...

HMM: turns out we've been over this already.  https://github.com/gracelang/language/issues/49#issuecomment-223725001

seems like Kim would *prefer* ==, != and friends in all objects, but is happy with a trait to include them.  I think the simplification of inheritance is worth it.

**Comment by apblack** [comment]
Yes, we did discuss this already, when I removed `==` from `graceObject` in _minigrace_.  I opened the issue again because of my realization that `::` didn't make sense without `==`.

What I propose it try in _SmallGrace_ is as follows:

1. `graceObject` is intrinsic.  It has the stringification methods, and _confidential_ methods `isMe(_)` and `identityHash`.  Because these methods are all intrinsic, they can do "magic" stuff.  (For example, the way that _minigrace's_ `asString` returns the name of the `class` or the `def` that created an object is "magic", in the sense that it looks at the context surrounding the definition.) 

2. The trait `identityEquality` (is `alwaysEquality` a better name?) adds methods `==` (defined using `isMe(_)`) and  `≠` (defined to be the inverse of `==`), and `hash` (defined using `identityHash`).  This can be in _standardGrace_: it requires no magic.  `identityEquality` will also define `::`

3. A trait `abstractEquality` (or maybe `nowEquality`?) requires the programmer to specify `==` and `hash`, and adds `≠`, and `::`.  It can also be defined in _standardGrace_.

A related point is that `requires` is not the same as `abstract`, I think.

**Comment by kjx** [comment]
> A related point is that `requires` is not the same as `abstract`, I think.

answered back at #32

**Comment by kjx** [comment]
> (is alwaysEquality a better name?)  
>  (or maybe nowEquality?)

yeah I think so. now, anyway.

**Comment by kjx** [comment]
we adopt the small grace design

**Comment by apblack** [comment]
You can see what's in SmallGrace [in the github repo](https://github.com/apblack/GraceInPharo/blob/master/Grace-Modules/standardGraceClass.grace).

Right now, the trait that implements identity equality is called `identityEquality`; I can certainly change that to `alwaysEquality`if we wish.  I suppose that there should also be a trait `abstractEquality`, or `nowEquality`, which would _require_ client-supplied `hash` and `==` methods, but would supply `::`, and `≠`.  That's easy to add.  There is also a type `EqualityObject` which is effectively what `Object` used to be:
```
    type EqualityObject = Object & interface {
        ::(_:Object) -> Binding
        ==(_:Object) -> Boolean
        ≠(_:Object) -> Boolean
        hash -> Number
    }
```
It describes objects with either of the equality traits.

**Comment by KimBruce** [comment]
Seems reasonable to me.

Kim
