### ISSUE TITLE
`super` is a bad notation

### ISSUE THREAD

**Issue by apblack** [gracelang/language#16]
Super is a bad notation in a language in which super is not a real object.  In Grace, `super` is not an object, rather, `super.` is a very odd notation for a statically bound request.  Grace should not have such blots on its escutchon!  We should either

1. make `super` a real object, i.e., adopt some sort of delegation semantics in place of inheritance.

2. come up with a better syntax for super-sends. `next method`, perhaps?

**Comment by kjx** [comment]
aliasing

**Comment by kjx** [comment]
drafted https://github.com/gracelang/language/blob/portland-james/spec.md#objects-classes-and-traits
