### ISSUE TITLE
Self or SelfType

### ISSUE THREAD

**Issue by apblack** [gracelang/language#160]
Which is it?

**Comment by KimBruce** [comment]
I thought it was Self, but don’t feel that strongly about it.  In other places i’ve written things like point: Point leaving the capitalization to distinguish between the two.  It seems reasonable to do that here as well.

Kim

**Comment by apblack** [comment]
`Self` it is.  I thought that we had used both terms in the Spec, ut apparently that was only in my head.  I'll fix the code ...
