### ISSUE TITLE
Does emptyList exist?

### ISSUE THREAD

**Issue by KimBruce** [gracelang/language#165]
What is the status of emptyList?  It is not listed in the documentation for the standard Grace library, yet it works.  In the header for list, it is suggested to write list[] to get an emptylist, though at the end of the description of the standard library it appears in the definition of a merge method.

Thus the question, should I teach my students emptyList or just have them write list[] (or does it matter)?

**Comment by apblack** [comment]
We decided, I think, to make `list` "module-like".   That is, we should have `list.empty`, `list.withAll(aCollection)`, `list.with(item1)`, etc.  Which does say whether a dialect should allow list, list(_), list(_,_), etc for creating empty and short lists.

**Comment by apblack** [comment]
I guess that the answer to this issue is that `emptyList` is deprecated.  It is no longer documented, but it still exists to enable a graceful migration to `list.empty`, rather than a lot of crashes.

**Comment by kjx** [comment]
Does say or doesn’t say?
