### ISSUE TITLE
insert (value) at (index) on lists?

### ISSUE THREAD

**Issue by KimBruce** [gracelang/language#166]
There apparently is no insert operation in lists to squeeze in a new element, moving some elements to the right to make room for the new one.  It seems odd to me that we have a remove(n) method, but no insert (val) at (m).  Obviously not a huge deal, it just seems a bit asymmetric.  (Of course we do have at(m) put (val).)

**Comment by apblack** [comment]
I'ld be happy to have someone implement this.  There need to be tests, or course, especially for the boundary cases of `m` being one beyond the end of the list, and being at the end of the list.

**Comment by KimBruce** [comment]
at(n)put(val) is in the interface.  I missed it.  Mea culpa!

**Comment by KimBruce** [comment]
Still needs to be written -- I'll take care of it.

**Comment by apblack** [comment]
This method was added in [minigrace commit 4d33d8a](https://github.com/gracelang/minigrace/commit/4d33d8a47770731cc46a31897b00da891aecbe04)
