### ISSUE TITLE
Stand-alone brackets should be operators

### ISSUE THREAD

**Issue by apblack** [gracelang/language#17]
Currently, `foo.[…]` is a method-request on the object named by `foo`, and can be re-defined, but in _minigrace_ `[…]` as a stand-alone expression invokes a built-in way of generating a built-in list.  It's not part of the Grace language, but my students see it and get confused.  It is certainly more elegant than `list.with(…)`

I propose that stand-alone `[…]` be brought into the language.  It should mean `self[…]` or `outer[…]`, just like any other recieverless-request.  It can thus be defined in the prelude and re-defined in any dialect.

While we are doing this for `[…]`, we may as well allow it for any other pair of matching brackets (except  for `{}` and `()`, which are already taken, and `‹›`, which minigrace has appropriated for non-interpolated multi-line strings).

**Comment by kjx** [comment]
> On 5/08/2015, at 2:33am, Andrew Black <notifications@github.com> wrote:
> 
> While we are doing this for [...], we may as well allow it for any other pair of matching brackets

I think this is in Kernan already

J

**Comment by kjx** [comment]
can we close this having defined [...] as defining [..]lists

**Comment by apblack** [comment]
`[ _ ]` is already an operator.  (It's also used to denote a lineup, but that's irrelevant for this issue, I believe.)  

This issue is about allowing _other_ bracket paris to be operators.  For example, `⟨_⟩`, and `⎣_⎦`.  Since all of the ASCII brackets are already accounted for, all of the pairs concerned are not ASCII.  So I imagine they Mr ASR-33 will hate this idea.

**Comment by kjx** [comment]
Kernan and this but it doesn't work now (I think). 

Andrew - do you want this or not?

**Comment by kjx** [comment]
I'm now anti brackets, anti-lineups, and anti-unicode...

**Comment by apblack** [comment]
I think that this is another idea that might be nice for an "industrial strength" or research language, but is probably be bad idea for a language designed for novices.  So let's keep the status quo, not make brackets operators, and close this issue.
