### ISSUE TITLE
Can two blocks be opened on the same line?

### ISSUE THREAD

**Issue by IsaacOscar** [gracelang/language#180]
Consider the following pointless code:
```
def x = if (true) then {{
   print("true")
}} else {{
   print("false")
}}
x.apply
```
I have in fact tried to write code like that in grace (where an if statement returns a block).

In minigrace this produces an error:
```
Syntax error: the prior line opened two blocks. There is no way for you to close them correctly! Please split the prior line into two.
```

However, in kernan it runs as expected.

From the spec, I see two relavent rules (emphasis mine)
> 3. If a line contains an unmatched opening brace, that line is said to open a code block. All lines up to the matching closing brace comprise the body of the code block, *and must be indented more than the line containing the opening brace*.
> 4. If the closing brace that closes the code block is the first non-space character on a line, then the indentation of the closing brace must be the same as that of the line containing the matching opening brace. **Otherwise, the line containing the closing brace must be indented like all the other lines in the code block.**

It seems in the line `}} else {{`, the first closing brace satisfies the first part of rule 4, however the second one contradicts the second part, since the line it is on is not indendented enough.
I suggest deleting the "otherwise" clause from rule 4, and adding the folowing bolded text to rule 3.

> ... All lines up to the matching closing brace comprise the body of the code block, and **if not begining with a closing brace** must be indented more than the line containing the opening brace.

Or if you think that my example should be rejected (why?) add a clarfication to the spec that this is intended; because it's quite subtle why this code violates the rules.

**Comment by apblack** [comment]
I think that the example should be rejected because a double opening brace is more likely to be a typo than to be deliberate.  A block containing nothing but a block _is_ very occasionally useful (I’ve used it once), but can be accommodated with more clarity using extra lines and extra indentation.

If others disagree and we decide to change the indentation rules, then we need a better change than the one proposed above, because the proposed change leaves the “otherwise” situation undefined.

**Comment by apblack** [comment]
I believe that the current indentation rules are fine.  In the more than three years that this issue has been open, no one has proposed better rules.   I have no problem with adding a sentence to the spec highlighting that this is deliberate, but don't think that it warrants too much ink.

**Comment by apblack** [comment]
Spec updated with counter-example in commit 5b2e1d0957ba91c1e963eae3c73e2dc7640a155f
