### ISSUE TITLE
Number Semantics

### ISSUE THREAD

**Issue by smarr** [gracelang/language#181]
This may or may not be a simple question.

My understanding from the last discussions I had on this topic is that the spec(*) leaves some room for how numbers are represented and what number types are actually supported.

Since I am cleaning up the Moth repository, and wanted to get the underlying SOMns tests running, I thought, I'd ask what the desired results for a few computations are:

```grace
print((4/3) + (4/5)) // → 2.133333

print(  1/  1)    // → 1
print(  3/  2)    // → 1.5
print(  4/ -2)    // → -2
print( -6/  3)    // → -2
print(-12/ -4)    // → 3
print(  7/ 2.0)   // → 3.5
print(  7/ 3.5)   // → 2
```

The annotated results are what I get on: http://web.cecs.pdx.edu/~grace/ide/

Could you confirm that those are the desired results?

Would also be great to know whether these values are supposed to have specific types.

Thanks!

*) I didn't check whether there were any changes to the spec.

**Comment by KimBruce** [comment]
Those all seem correct to me.  The types of all the answers are Number.  Is there any other option for the types?

**Comment by smarr** [comment]
The spec is still a fuzzy around that:

> In Grace, numbers are objects. Grace supports a single type Number, which accommodates at least 64-bit precision floats. Implementations may support other classes of numbers, and may define types that extend Number; a full specification of numeric types is yet to be completed.

I thought, I just ask, in case opinions developed since the last time I looked at this a year or more ago.
