### ISSUE TITLE
Should we keep implicit `return`?

### ISSUE THREAD

**Issue by apblack** [gracelang/language#29]
I found that some students were confused by when they needed to say `return` and when they didn't.

After our discussion with Sam Livingston-Grey, I started to think that maybe we should just require `return` everywhere that a value is to be returned.

**Comment by kjx** [comment]
but what do we write when no value is to be returned?
return done

or just not "Return" anything and done is returned by, well, magic?

**Comment by apblack** [comment]
Same as now: we write `return`.   This returns with the value `done`.

If the code falls off the end of the method without returning, it also returns done.   This may of may not be a type error, depending on the method header.

The main objection to this is that in the case of trivial methods returning a constant, the method body becomes twice as long:

    method isObject { true}

becomes

    method isObject { return true }

Longer, but arguably clearer.  I'm somewhat ambivalent.  Requiring `return` does eliminate a choice.

**Comment by kjx** [comment]
`
Under this proposal, I would have to write return result, and failing to do so would be a static error (assuming that I wrote -> SomeTypeOtherThanDone in the method header).
`

If we had a working static type checker dialect, that would often catch the error even in the current language. 

`
 I'm somewhat ambivalent. 
`

 I think this can also be enforced in a dialect. I propose either:

1. we do not make this change in the core language at this point, or, 
2. if you feel strongly about it, we just do it.

**Comment by KimBruce** [comment]
I’d prefer to leave it as is.  Most of the time it makes the code cleaner and encourages student to terminate the method at the end of its code (giving a single return spot — which many people have argued is easier to understand).  I’ve used that for long parts of the course and only much later taught return as a way of breaking from a method.

It is certainly easy enough to enforce the more restrictive rule (always use return) in a dialect.

Kim

**Comment by apblack** [comment]
We won't make the change.  A dialect can always enforce the use of `return` if a teacher think it wise for their students.
