### ISSUE TITLE
Replace lists of multiple arguments with "tupling"

### ISSUE THREAD

**Issue by apblack** [gracelang/language#3]
Suppose that comma generates a tuple (as it does in Python).  Then the expression `("Nyssa", 10)` is a 
String-Number-Tuple, and the request
```
create("Nyssa", 10)
```
requests the method `create` with a single argument (which is a tuple).  We would still write the body of the method in the same way as now

```
method create(name:String, height:10) {
    object {
        print "created {name}, who is {height} inches tall"
        method speak { print "woof" }
        ....
    }
}
```
where a parameter list with multiple comma-separated names performs "de-tupling".

We could also re-purpose the `*p` notation in a parameter list to mean that `p` is bound to the whole tuple, so that `list.with( 2, 3, 5, 7, 11, 13, 17)` is a request on `list.with` with a single tuple argument, and

```
method with(*elts) {
   ...
}
```
binds `elts` to the _whole_ tuple.  We would have to design a protocol for tuple access.

Since Grace does not allow overloading by arity, I think that we don't loose anything.   It should be possible to  statically type tuples (unlike sequences of objects).

**What do we gain?**

* We can get rid of variable arity-methods, and use tuple arguments instead.  Unlike variable-arity argument lists, which can only be treated as collections, tuples can *either* be exploded, or passed on to other methods that take tuples. 

* We also gain multiple return-values, which are currently missing.   This would be very useful in designing libraries.  For example, suppose that we give iterators a `with` method, so that
```
(iteratorA.with(iteratorB))
```
answers a new iterator that yields 2-tuples.  Then we could write
```
(iteratorA.with(iteratorB)).do { a, b ->
   ...
}
```
where the block is applied to a tuple of arguments.   (We could do this now for `twoIterators` and `threeIterators`, but not for the general case.

**What would we have to add to the language?**

* A syntax for binding a set of identifiers to a tuple
* A (perhaps slightly different) syntax usable in a method and block headers to decompose a tuple, so that method headers with multiple argument lists look the same as they do now
* Re-purposing `,` as the tupling operation.

Not clear what to do about empty tuples and tuples with a single element.  Python's (3,) is ugly.

**Comment by KimBruce** [comment]
This seems like a significant change that might have ripple effects through the language, and hence makes me nervous, especially as I'm not sure about all the places where ","s appear in Grace.  (What about generic types, for example, where we write Dict<K,T>?)

It does create a bit of ambiguity about how one would specify static typing for a method.  We could write:
```
method m (a: T,b: U) -> V
```
or
```
method m (c: Prod<T, U>) -> V
```

We had talked about providing tuples early on, but dropped that idea, though of course I have no memory as to why.  Hence, consider me hesitant at doing this at this late stage.

**Comment by kjx** [comment]
> On 4/08/2015, at 10:49am, Kim Bruce <notifications@github.com> wrote:
> 
> We had talked about providing tuples early on, but dropped that idea, though of course I have no memory as to why. Hence, consider me hesitant at doing this at this late stage.

I understand the problem is that if you “get the arity wrong” on a method without argument types, odd things will happen

method foo(x) { … }

does this take a single argument “x’ or an undecomposted tuple.
If a tuple is passed in by accident, you’ll get an odd error later on.

I believe (Michael?) that Python2 used to do it this way but changed in python 3.

https://www.python.org/dev/peps/pep-3113/

J

**Comment by apblack** [comment]
Python 2 and Python 3 both have tuples.  What was in Python 2 but was dropped from Pythom 3 was the automatic de-tupping in a parameter list.  Now you have to write a separate 

```
a, b = parameter
```

de-tupling assignment in the body of the method.

**Comment by kjx** [comment]
The question "should we have tuples" is a different question to should we replace multiple arguments with tuples.

Another related question is: should we replace varargs with collections 

J

**Comment by apblack** [comment]
In Claremont, we agreed to delete variable-arity methods and add sequences.  We didn't talk about tuples.  We also didn't decide on a syntax for sequences.

One possibility for a sequence syntax is to re-purpose minigrace's [ and ].   This has the disadvantage that we can't keep [ and ] as an operator and _also_  treat [ and ] as a delimiter pair that encloses an argument.  That's because a[x] might then mean _either_ "request the [ ] method with argument `x` and receiver `a`", _or_ "request the `a` method with argument `sequence(x)` and receiver `self`.

Another possibility is to use another set of brackets, like ⟨ and ⟩, but whatever set we use, it can't also be available as an operator, for the same reason that this is problematic with [ and ].

A third possibility is to use something ad-hoc, like sequence(item1, item2, item3).   This is readable, but requires extra parenthesis when used as an argument.

A fourth possibility is to seriously consider this issue — tupling — and see if tuples give us a better "out".

**Comment by kjx** [comment]
> On 23/09/2015, at 9:36am, Andrew Black <notifications@github.com> wrote:
> 
> A fourth possibility is to seriously consider this issue — tupling — and see if tuples give us a better "out”.

I don’t see how tupling helps unless you have variadic tuples
aka heterogenous (potentally typed) lists.   
I think there are type systems which support that but they are quite 
sophisticated. 

On the other hand, 
 a) the old varargs is pretty much a special case of this right now, and
 b) this is currently way down the priority list :-)

J

**Comment by kjx** [comment]
Deciding the interface of  [..] lineups - #51 - will go a along way towards handling this. 

Alternatively, we could consider writing 

    create ["Nyssa", 10]

or

    tuple ["Nyssa", 10] 

or (Scheme-ish)

    values ["Nyssa", 10]

or (Smalltalk-ish) 

    tuple "Nyssa" and 10 

or (Self-ish) 

     tuple "Nyssa" tuple 10 


Where the fun really beings here is doing the Right Thing™ with the types.  Proving Michael right: 

    tuple<String> "Nyssa" tuple<Number> 10 

but I'd much, much, rather not have to write those types in, and get them even dynamically
