### ISSUE TITLE
Once methods, or lazy defs

### ISSUE THREAD

**Issue by apblack** [gracelang/language#31]
One of Bertrand Meyer's points from his ECOOP talk was that "once" was an important pattern, worthy of being put into a language.  __def__ is sort of like once ... but not quite.

**Comment by kjx** [comment]
yeah. 

Scala Lazy Value.

https://projects.cecs.pdx.edu:8443/~black/NewOOL/index.cgi/wiki/LazyInitialisation

whether this gets rid of all the init problems or not I doubt - J

**Comment by apblack** [comment]
My bad for opening two issues on the same topic.  Let's continue this discussion in #41.
