### ISSUE TITLE
Too much redundancy with new constructs

### ISSUE THREAD

**Issue by apblack** [gracelang/language#33]
Now that we have introduced some form of lexical binding (aka "let"). I'm concerned that there is too much redundancy in Grace, in the sense that there are too many ways of saying the same thing.   We already had to explain to students that it really didn't matter whether they made a class parameter `x'` public by writing `method x {x'}` or by wrting `def x is public = x'`.  Now we also have to explain that, within a method, a temporary constant can be introduced either by `let x = ...` or by `def x = ...`.

Note that I an _not_ questioning the need for a lexical binding construct.  However, now that we have it, it seems to me that we no longer need `def`.

`def` is used mostly for local constants --- replaced by `let` --- and for public methods (when annotated `is public`) that avoid recomputing the accessed value --- replaced by "once" methods.   So it is small loss to remove `def` altogether.

Actually, what we should do is repurpose the `def` keyword to mean a lexical binding.  So `def`s cannot be overridden.

I don't think that we loose much, except some redundancy.  Now methods and public vars are the only way to expose attributes of an object.

**Comment by kjx** [comment]
On 24/09/2015, at 10:47am, Andrew Black <notifications@github.com> wrote:
> 
> Note that I an not questioning the need for a lexical binding construct. However, now that we have it, it seems to me taht we no longer need def.

well this are the kinds of editing and ensuring things are consistent we now need to do!…

I certainly figured don't need both “let” and “def … is static”.

James

**Comment by kjx** [comment]
This is part of the larger question of the definition of manifest #47

**Comment by kjx** [comment]
Do we want 'let'?  Do we need 'let? now?  Currently not in the draft.
