### ISSUE TITLE
Unhelpful rant about Semantics of Traits and Trait Composition

### ISSUE THREAD

**Issue by kjx** [gracelang/language#39]
I don't want to re-open #38 because I see no other way to make progress. But I got a working Internet for a bit, so I wanted to record my questions about this proposal --- even though doing so is by definition "unhelpful".  That's why I closed this one too.

**Comment by kjx** [comment]
Quotes are from #38.

### trait constructors 

```
We might want to introduce a way of eliminating the automatic inheritance, e.g.,
**inherits** `nothing`, where `nothing` is a pre-defined identifier.
```

Question: how is "nothing" (which is a class/factory method defined)?
Is it  just `trait { }`  or am I missing something?

Question: if you can do that, why do you need trait constructors.  Could the trait shorthand construt objects that **inherits nothing**? 

> I propose that we invent a syntax for trait constructors

Question: are both trait and object constructors conceptually (parallel) primitives?
(Arguably Strings & Number literals are glosses for object constructors;
blocks are a bit more special I guess).
Question: can **object constructors** define traits? (I don't think so, because object's have default methods)
Question: can **trait constructors** define objets? (no, because trait construtors encore the implicit requirements for being traits)

Question: doesn't this mean we have just changed the fundamental conceptual basis of Grace from one based on only objects, to now being based on objects and traits? 

> [An alternative syntax using the annotation is trait on an object constructor isn’t legal, because trait is a keyword, and annotations require identifiers.]

Question: why not use another annotation?  E.g. how about **implicitTrait** meaning a trait defined implicitly, rather than with the trait shorthand?  That means we could talk about:

- [unannotated implicit traits] --- methods return object constructors that happen to meet the requirements for traits
- [annotated implicit traits] --- as in 1. but annotated **implicitTrait** so the requirements can be checked.
- [explicit traits] --- defined by the trait shorthand, which produces a method returning an annotated implicit trait. 

Observation: this same scheme would work for classes too
Observation: note that this scheme doesn't work because we're annotation the constructor, not the method containing it.
Obeservation: annotate those methods as e.g. **factory** or **implicitFactory** ? 
 

`The purpose of the trait constructor is to provide error messages if a programmer inadvertently breaches the trait restrictions. Note that, as a consequence, `graceObject` is itself a trait, and can be used by an object that wishes to re-acquire one of the default behaviors.`

Question: isn't the purpose of trait constructors also to allow the construction of what-used-to-be-just objects but that do not have the default/magic method? 

> Any object that satisfies the restrictions on traits (contains only methods and types) is defined to be a trait, and can be used by another trait or object.  

Question: doesn't the spoken word "trait" now have three meanings:  trait constructor; trait shorthand; any object that implicitly meets the restrictions explicitly guaranteed by trait constructors and the trait shorthand? 



> syntax for trait constructors [is] the same as the existing syntax for object constructors, except that it is preceded by the keyword trait

Question: so do you propose we now write: 
 `trait { ... }` as a trait constructor
 'trait foo { ...}' as trait shortcut (method return a trait constructor)
 `object { ... }` as a object constructor
 'class foo { ...}' as a class shortcut (method return a object constructor)

Question: We now have one keyword with two distinct systematic forms - are there any others in Grace like this?   What if people write `def bar = trait foo {}`. Why do traits get two forms with the same keyword, while object and class have different keywords? 
 

### Inheritance

> 1.  Any object constructor can contain an **inherits** statement that refers to
>     a fresh object.  This fresh object will become the superobject of the [generated object]

Question: do the "fresh object" the "super objet" and the "generated object" have the same identity? Are they distinguishable? 

> 2.  An *overriding definition* means a definition written in the body of the
>     object constructor.

Question: don't traits override classes?   So isn't a declaration coming in from a trait an overriding declaration?  

> 3.  The **inherits** statement can be modified by an **alias** clause

Question how do you write this alias clause?  What about arities?   #37

>     Question: should the default visibility of names introduced by **alias** be
>     confidential?  This is usually what one wants, but it’s inconsistent with
>     the default for other methods.

Answer: I think so, if the main aim of these definitions is to support reuse (e.g. replace super).

Question: but why not make them the same as the overridden version?
Question: what about other annotations? are they carried along?
Question: does alias have an **is** clause to add annotations? What semantics?

> 4.  The **inherits** statement can be modified by an **exclude** clause, which

Question: what about arities?  (same as for aliases?)  #37

> 5.  Overriding definitions for types are not allowed.

Question: why ban this in the core language, not in a dialect? 


### Trait Use

>     -   The sum of a trait containing an attribute named `a` with another trait
>         containing an attribute named `a` is a trait with an attribute named `a` whose
>         body is the join of the bodies of the bodies of `a` in the composition.  ...  
>         We can approximate equality
>         conservatively; in particular, if the two bodies are parameterized, we
>         can assume them to be different, even though the value of the parameter
>         might be the same in both cases.

Question: what is the conservative approximation? Is it in the spec or left to the implementation?
Question: many traits will be type-generic. Doesn't that mean they are parameterised?
Quetsion: doesn't that mean this only works (in practice) for traits written to be _dynamically_typed, not _statically_ typed?  
Question: wouldn't changing a trait from dynamic to statically (parameterised) typing change the combination behaviour of that trait?

```
7.  Once the locally-defined attributes have been added, it is an error for the
    generated trait or object to contain a method whose body is *traitConflict*.
    Ideally, this error will be reported statically.
```

Question: do you mean: this error **must** be reported dyncamilly when the method is called, and **may** be deteteced earlier by a dialect, or this error **must** be detected statically? 

> 8.  An object constructor that **uses** traits can also inherit. If it does so,
>     the first phase of inheritance (attribute collection) takes place *before*
>     any trait methods are included in the generated object, and the second phase
>     of inheritance (initialization) takes place *after* all trait methods and
>     local methods have been included, as described above.

Question (for what it's worth): after reading this para, I thought "ahah!" --- if we  *really* want these asymmetric overriding semantics, couldn't we change the Pomona semantics to do the same thing: bring in class attributes, have them override by a combination of traits, then have them override by the local definitions? 
Observation: I still don't like traits silently overriding classes.   But making progress is the most important thing. 

### Default methods

> Before traits, all objects by default inherited a few useful methods, notably `=`, `≠`, `::`, and` asString`.  

Question: spec is inconsistent. It says **done** has only asString and asDebug string, not even "==".. Other methods in this list include "!=" and hash.  I think at one point we talked about "dynamicType". 

> This means, for example, that you can’t put a trait in a dictionary (at least, not in the usual way.)

Question: can you put a trait in a "[..]" lineup? why or why not?
Question: where does putting a trait in a dictionary fail, and why? 


> But the loss of `asString` and the concomitant ability to print any object is a practical problem.
> I’m concerned that not having `asString` will become a problem
> Perhaps the best thing would be to try getting along without the kludge (so that traits don’t have an asString)

Question: How about trying to get along without **any** magic methods?

- I think "asSting" and "asDebugString" are both mostly for debugging --- or rather, having the uniformly available is mostly for debugging.  But isn;t that functionality that should be supported by the debgger (if we had one) rather than contorting the language? Self does this with some reflective object printing support (including a builtin hittable that gives objects identity numbers): we also have the option of the debugger/ide/ repl  trying "asString" if it is defined, and if not (or if that fails) resorting to some default printer. 

- "==" and "!=" seem pretty useful, but done (currently) doesn't have them (although it does in Kernan). Question:  why should every object be comparable? Ask William Cook?  
Question: is every object an Object?    Could we  make type **Object** have those methods, graceObject supply them (although I like traits.equality better) but Object doesn't have to be the very top type, and we can have objects.  If a collection (e.g. for "Contains") needs == then it had better take "Objets" or "Eq" or something Haskellian...

- Question: "hash" and "::" are still useful, but surely less so than "==" are they so important every object must have them?   Perhaps writing pair(a,b) isn't so bad; perhaps [a,b] can do much of what :: does,  (I recall someone asking for tuple accessors in [..] lineups) 
- Quetsion why are hash tables privileged over binary trees? (hash is in Object, but the comparable operators aren't) 

Observation: we can still add in graceObject or whatever  by default via the class shortcut, or e.g. traits.equality (by analogy with hassles' "deriving equals" but out default is identity, not structural) and traits.printable (ditto)  if that's what people want to do.  But not doing this by default means we don't need two kinds of primitive constructors. 


### bigger questions

> (I would like to see a drastic simplification of inheritance, but that is *not* part of this discussion.)  

If not now, then when?    https://github.com/gracelang/language/issues/21#issuecomment-183285366

Question: what would you propose James?

1. eliminate "default" methods.  Deal with asSting reflexively, the rest via types (or type bounds)
2. eliminate the "meet" of bodies because it doesn't make sense
3. ban diamonds (probably in dlalects) a la donna malayeri style, so the meet could never arise
4. If traits must always silently override classes, we can do that with a tweak to Pomona. But it's better if they don't. 
5. Observation: this means out model for inheritance is broad and shallow, rather than narrow and deep. Most of the time we'll want classes that mix in lots of traits with little or no inheritance!   
Inheritance would have two main remaining uses: instantiating abstract classes in frameworks (so the kids don't have to redeclare every variable); and "conceptual modelling" in domains, where again an abstract root would mix in most of the traits...

**Comment by apblack** [comment]
My proposal to allow **trait object** { ... } in addition to **object { ... }** exists for three purposes.

1.  To allow programers to be more explicit about their intentions.
2. To give programmers checking form the compiler, which would complain, for example, if a **def** is accidentally written in a trait.
3. Not inheriting from `graceObject`.  We could say **inherits** **trait** {}`, but only if traits don't inherit from `graceObject` implicitly, so this seems circular.

**Comment by kjx** [comment]
I did figure this would be another unhelpful rant:

> 1. To allow programers to be more explicit about their intentions.

Yes this is good, but I don't see that it should need a construct on the same conceptual level as object constructors.  

> 2. To give programmers checking form the compiler, which would complain, for example, if a def is accidentally written in a trait.

Again yes I agree with this: but again, it's not clear why this has to be at such a low level in the scheme of things (or at least in the scheme of things inside my own head --- which is clearly nowhere else!).  If type checking is pushed off to a dialect, can't this be in a dialect too?    On the other hand: things that are pushed off into dialects don't get done. 

> 3. Not inheriting from graceObject. We could say inherits trait {}, but only if traits don't inherit from graceObject` implicitly, so this seems circular.

We could say `inherit nothing`  or `inherit graceTrait` to override the default inheritance from graceObject. but that raises the question of how to implement "nothing".  Nothing could almost be 'done' couldn't it? 


I wonder if there is another purpose to the design (that we have adopted: I don't want to reopen the issue): to support a really straightforward implementation of traits -- by just copying methods from traits into objects?   But: if any object that meets the requirements for being a trait can be a trait (even if declared with an `object {}`), I don't understand if these mechanisms (trait {} in particular) can help much at that end?

**Comment by apblack** [comment]
kjx, you make a couple of very valid points.  The _explicit intentions_ goal and the _checking_ goal of the **trait object** and **trait** syntaxes could be accomplished by annotations, along with a dialect that checked them.  

Changing the default inheritance could not be so accomplished.   We could, as you suggest, eliminate all default inheritance; this would certainly be the "right thing" from a _formal_ perspective.  But it would not meet our goal of being friendly for novices, or of making "good" programs shorter than "bad" programs.   C++ ends up with a mess because _not_ everything is an object.  Being able to `print` any object is _really_ helpful when debugging.

I suppose that we could make the `is trait` annotation remove the default inheritance from the object that the annotated construct creates.  This would violate our rule that annotations don't change the semantics, but them `is readable` and `is public` already do that.  

By the way, `done` has an `asString` method, by design.  It enables messages like "done does not have method `add`" when a programmer forgets to return the right thing.   Hence it is different from `nothing`, which would have no methods at all.   `done` does not have =, ≠, etc, and thus does not have type Object.   I suppose that we could make `done` have no methods at all, and use some meta-programming in the error message printing code, along the lines of

    def targetMirror = mirrors.reflect(target)
    if (targetMirror.methodNames.contains "asString") then { 
        target.asString
    } else {
        if (_prelude.isIdentical(target, ???) then { "done" } else { "unprintable object" }
    }

But what do we write in place of the ???.  To **use** `done`, itmust be an object generator, not an object, so every `done` would have its own identity.

**Comment by kjx** [comment]
### printing

> Being able to print any object is really helpful when debugging.

I know, and I agree. And also, being able to override that with asString or asDebugSting (or "show" or "showString") or something is also important.   But that doesn't have to mean that even asString must go into the type "Object"?  

My rationale here comes from experience with Self, which didn't have any "default methods" - although almost all objects implemented them, the IDE didn't rely on them. Rather, we'd do something more like Self. At which point I sketched code then deleted it because it was _exactly the code you'd written above_.   

> But what do we write in place of the ???. To be able to write `uses done`, **done** must be an object generator, not an object, 

How about: 

` if (targetMirror.size == 0) then { "done" } else { "unprintable object" }
`

> so every `done` would have its own identity.

I don't know what identity means for an object with no state and no methods.


### Annotations... 

> I suppose that we could make the is trait annotation remove the default inheritance from the object that the annotated construct creates.

I don't think we should do that. I think that the issue of whether an object "meets the requirements for a trait" or "is an implicit trait" -- and whether that can be checked --- can be decoupled from the issue of whether that object has the default methods.  

> This would violate our rule that annotations don't change the semantics, but them is readable and is public already do that.

yeah. at some point we need to sort this out. Haven't wanted to come it too hard as Tim was supposed to be doing it, but we do need a model sometime soon!    But isn't this an 'unrelated issue'


### The Protocol for All Objects

> C++ ends up with a mess because not everything is an object

I can see a difference between _eveything is an object_ and _everything is an Object_ (the second meaning: implements the protocol of all objects).  Even in Smalltalk (or Pharo) these days, ProtoObject is above Object (although Pharo's ProtoObject still has 28 methods!).  I'm **not** suggesting that we have things that aren't conceptually created by object constuctors (considering blocks as rather special object constructors). I am asking whether everything created by object constructors has to implement this set of default methods.

**Comment by kjx** [comment]
meant to add:

> The explicit intentions goal and the checking goal of the trait object and trait syntaxes could be accomplished by annotations, along with a dialect that checked them

yes, that's just right.

**Comment by apblack** [comment]
The line of reasoning that I am exploring here is that objects that are traits don't have default methods.
So either we remove default methods from _all_ objects, which I think is bad for novices, or we make the rules for traits different from those for other objects.  

That was why I said:

> I suppose that we could make the `is trait` annotation remove the default inheritance from the object that the annotated construct creates.

You said: 

> I don't think we should do that.

What do you then propose instead?

Remember, we all agreed that it would-be good to have `egal` defined to all objects, exactly because it would make life easier for novices (until we decided that this was infeasible in the presence of closures).

**Comment by kjx** [comment]
> The line of reasoning that I am exploring here is that objects that are traits don't have default methods.

yep. And that does make sense!

> So either we remove default methods from all objects, which I think is bad for novices, or we make the rules for traits different from those for other objects.

"Making ... traits different from all other objects" (I know thats not quite what you said) seems to me that we then have two base level things, objects and traits, because we cannot translate object constructors into trait constructors if the objects are not actually implicitly defining traits.  This is why I see two separate things going on here: leaving out default methods, and checking the trait requirements.  If we have something that leaves out default methods, but doesn't check the trait requirements, both classes and traits can be translated into that.    I like the conceptual economy of the **class** form adding default methods if not already, the **trait** form explicitly checking the traits, and the **object** form doing neither, doing just what it says on the tin.   That does make object-first programming a bit harder, but only a bit; expecting fewer (ideally no) default methods makes it a bit easier again.

> Remember, we all agreed that it would-be good to have egal defined to all objects, exactly because it would make life easier for novices (until we decided that this was infeasible in the presence of closures).

Yes, and over the last year or longer I've changed my mind, basically.   Non-overridable **egal** doesn't seem as easy as I hoped (I dunno how clojure does it) --- or perhaps a variant does: a "class test"; then identity for any mutable object; recurse field-by-field for any immutable/value object.  I'm hewing more and more to the OO / coalgebraic position that if objects want to offer "==" then they can, but they shouldn't have to (as with < for example).  == is the last bastion of functional programming!  This is also informed by the work with Sophia on the minimum necessary to support trust in OO systems, and I really mean to write up the rationale. Really.   Grace should offer traits with identity based ==, perhaps a (lightly reflexive) "egal" version that only makes sense for records/value objects, that objects can choose to opt into or not; and OK a separable, micro-based reflexive/debugging API that perhaps can burn through abstraction and encapsulation boundaries and answer "==" if you work really hard.

**Comment by kjx** [comment]
> What do you then propose instead?

I was trying not to. But (after getting up this morning I thought of)

- **Objects** for James with no default anything
- **Traits** for Andrew (an **implicitTrait** annotation on object constructors, and the existing generative **trait** shortcut)
- **Classes** for Kim with default implementations that come in by default by using a trait if they don't already inherit it. 

Most reusable code would be written using traits.  Most instantiable code would be written using classes.
They would translate down to objects.  

Or, more negatively, from the end of the long long comment above: 

1. eliminate "default" methods. Deal with asSting reflexively, the rest via types (or type bounds)
2. eliminate the "meet" of bodies because it doesn't make sense (note: same reason as egal not making sense)
3. ban diamonds (probably in dlalects) a la donna malayeri style, so the meet could never arise
4. If traits must always silently override classes, we can do that with a tweak to Pomona. But it's better if they don't.
5. Observation: this means out model for inheritance is broad and shallow, rather than narrow and deep. Most of the time we'll want classes that mix in lots of traits with little or no inheritance!
6. Inheritance would have two main remaining uses: instantiating abstract classes in frameworks (so the kids don't have to redeclare every variable); and "conceptual modelling" in domains, where again an abstract root would mix in most of the traits...

I also wondered about an "includes" operator, but will write later: have to drive from Rotovegas to Wellington....

**Comment by apblack** [comment]
> 
> eliminate the "meet" of bodies because it doesn't make sense

It makes perfect sense. It's just uncomputable, in the general case 😖

It is computable, though, in the common special case of unparametrized traits without state or closures. 

But it's a convenience, not an essential feature. It's always possible to patch things up with `exclude`.

**Comment by kjx** [comment]
> It makes perfect sense. It's just uncomputable, in the general case 😖

Heh. So we'd need to specify an approximation in the spec...

> It is computable, though, in the common special case of unparametrized traits without state or closures. 

Again - for traits that aren't even type-generic. 

> But it's a convenience, not an essential feature. It's always possible to patch things up with `exclude`.

Right. Well that's good - the model is simpler without it.  Again, this also goes to the amount of overriding we expect. If we aim for broader, shallower hierarchies, without much class or even trait inheritance with overriding, this won't be a problem

That's Donna Makaieri's idea: do MI and just ban diamonds - which we should be able to do, maybe even just in a dialect. Basically if you get something that may be a meet (ignoring closures, parameters etc) then the whole composition is illegal.

I dont think this is because not taking out meets is necessarily hard to specify or implement, but it does have nasty corner cases.  Traits avoid some of those wrt state and initialisation. Cutting out diamonds avoids more of those corner cases.

**Comment by kjx** [comment]
I am aware that "Objects for James, Traits for Andrew, Classes for Kim" does sound like the most egregious bit of design-by-committee I've seen in a long time.   On the other hand, I actually think it is a good design that is quite defensible, and that puts those three ideas together rather better than most other attempts.

**Comment by kjx** [comment]
Answering my own question:

> We now have one keyword with two distinct systematic forms - are there any others in Grace like this?

yeah: **type**. I propose we fix that, by renaming structural type literals as **interfaces* #42

**Comment by kjx** [comment]
Some related ideas that are **not** proposals and I didn't know where else to put them.

### excludes interface ###

writing **excludes interface T**   as a synonym for writing down all the methods in the interface of type T. 

Given  (modulo #42, #45) this definition

```
type Equals = interface { 
   request == (x)  
   request != (x) 
}
```

we could write 

```
use someRandomTraitWithDefaultMethods
  exclude type Equals
```

to mean 

```
use someRandomTraitWithDefaultMethods
  exclude ==(x)
  exclude !=(x)
```


This should be a low priority.

### include and include type ### 

We could also have **include** and **include type** so e.g. 

```
use someRandomTraitWithDefaultMethods
use someOtherRandomTraitWithDefaultMethods
use theTraitIWantToGetEqualsFrom
  include type Equals
```

To mean get all the methods in Equals from that trait --- ideally by promoting them to pseudo _local definitions_ so attempts to override them will lead to errors... 

But now we have the option of slicing and dicing up traits, which is a step to far for me. I'd much rather that this was done on the definition side (not the using side); none of those traits would define Equals at all (traits should be minimal), and you'd have another trait what had the equals behaviour you wanted.


```
use someRandomTraitWithDefaultMethods
use someOtherRandomTraitWithDefaultMethods
use theRestOfTheTraitIWantToGetEqualsFromButThatDoesntHaveEqualsAnyMore
use theEqualsBehaviorThatIWantRefactoredOutOfTheAboveTrait
```

**Comment by kjx** [comment]
earlier, talking about the meet:

> It is computable, though, in the common special case of unparametrized traits without state or closures.

but we have lexical scope and traits are generative.  So every method in a trait is in closure.

**Comment by kjx** [comment]
Note that if objects don't have default methods, and classes only add in a default inheritance if syntactically there aren't any other inherits/users cases, a class that inherits from something without default methods won't get default methods either.  

A class that only inherits from classes cannot have this problem however --- so perhaps standard grace should require class to only inherit from things with default methods (classes), and to always have an inherits clause or get a default inherits (not uses) clause.  

I don't like classes being more clever (e.g. seeing if there are the default methods and then adding them in) because that behaviour can be unpredictable

**Comment by apblack** [comment]
> but we have lexical scope and traits are generative. So every method in a trait is in closure.

No.  Every method might _potentially_ contain a closure.   Most will not.

**Comment by kjx** [comment]
Isn't every method closed over all enclosing scopes?  

I much prefer your earlier comment:

> But it's a convenience, not an essential feature. It's always possible to patch things up with `exclude`.
