### ISSUE TITLE
What should `for() do()` mean?

### ISSUE THREAD

**Issue by apblack** [gracelang/language#4]
Currently `for() do()` means something like
```
method for(coll:Collection<T>)do(action:Block1<T,Done>) -> Done {
    def iter = coll.iterator
    while (iter.hasNext) do {
        action.apply(iter.next)
    }
}
```
We could instead make it mean
```
method for(coll:Collection<T>)do(action:Block1<T,Done>) -> Done {
    coll.do(action)
}
```
It's much easier to write a `do` method on a collection than it is to build an iterator.  (Consider a binary tree, for example.)  The second translation is much easier to explain, and more efficient in implementation.  What's not to like?

**Comment by KimBruce** [comment]
If there is no downside then let's do it. Is be happy to deemphasize
iterators in favor of methods that take actions as arguments.

**Comment by kjx** [comment]
The downside is internal iterators are less flexible 

consider “zip”  (aka collection.with( anotherCollection) do { first, second ->  … }

**Comment by apblack** [comment]
Let's assume that we have the `.with` method, to produce zip lists.  (I have the code, but couldn't decide where to put it.)  Then these can have a `do` method as you illustrate above, except that you omitted the `.`

But one can't use them with `for`, unless we accept my "tuples" proposal (#6), or makes them the zip iterator return a list.   This is because the block of a `for … do` gets only one argument.

External iterators are more flexible than internal iterators.  Suppose that you want to iterate through two collections, always deleting the minimum element (as in the merge of two sorted lists.)  You can do this with two external iterators, but not with two internal iterators.  You can't do it with a `for`, though, so it's irrelevant to this discussion.

**Comment by kjx** [comment]
> On 11/08/2015, at 02:49, Andrew Black <notifications@github.com> wrote:
> 
> External iterators are more flexible than internal iterators. ... You can't do it with a for, though, so it's irrelevant to this discussion.

Inasmuch as this discussion is about what our core iteration protocol should be, it seems relevant to me

J

**Comment by apblack** [comment]
I didn't think that I was proposing (here) that we make any changes to the core iteration protocol.  The issue here is whether `for()do()` should be implemented using external iterators or internal iterators.

By all means open another discussion on what the iteration protocol should be.  Perhaps iterators should have remove, or reset?  But lets not do that here.

**Comment by apblack** [comment]
We discussed this in a rather rushed way in Claremont.  I didn't hear anything arguing that we should not define `for()do()` as equivalent to `do()`.  We might add `for()and()do()` to the standard prelude, and that could be defined as a `do` on the first argument and an `iterator` on the second.

**Comment by KimBruce** [comment]
Fine with me.

**Comment by apblack** [comment]
Changed documentation.  Implemented for()and()do() in standard prelude.
