### ISSUE TITLE
should we require 'method' in type declarations?

### ISSUE THREAD

**Issue by kjx** [gracelang/language#45]
we write something like  (modulo #42) 

```
type Foo = interface { 
     a 
     b
```

should we write

```
type Foo = interface { 
     method a 
     method b
```

or 

```
type Foo = interface { 
     request a 
     request b
```

instead?

**Comment by KimBruce** [comment]
The third is unacceptable (why introduce a new keyword), and I don't see the purpose of making the change from one to two.  We have enough real issues, let's not make up new ones unnecessarily!
