### ISSUE TITLE
valof as top level "control method"

### ISSUE THREAD

**Issue by apblack** [gracelang/language#52]
Should we have a top level method in standardGrace (the main dialect) that does essentially what BCPL's **valof** did, but without **resultsis**.  That is: take a parameterless block as argument, evaluate it (i.e., request it to `apply` itself), and return the result.

Thus:

    def constant = valof {
        def local1 = ...
        def local2 = ...
        complicated expression involving locals }

this would be exactly equivalent to 

    def constant = {
        def local1 = ...
        def local2 = ...
        complicated expression involving locals }.apply

which is a common idiom in JavaScript.

If we think we should, what do we call it?  `value`?  `valueof`?  `valueOf`?  `begin`? `prog`? Or something else?

**Comment by KimBruce** [comment]
Call me conservative, but I'm not sure I see the need for this.  Replace if by your "exactly equivalent" expression except just define the parameterless method, sm, that does the computation, and then write
   def constant = sm
It does leave sm visible to subclasses, but I don't see that as a big deal for our target audience.

I have run into this a couple of times while coding, but it is easy to code around.

**Comment by apblack** [comment]
It's just a method in a library!

**Comment by kjx** [comment]
in standard library as name **valueOf**
