### ISSUE TITLE
Should && and || allow blocks as their argument?

### ISSUE THREAD

**Issue by apblack** [gracelang/language#6]
Code that uses `orElse` and `andAlso` is hard to read.   Binary operator symbols are much more readable.

For example, compare
``` 
elseif {(o.value.kind == "member").andAlso {
        o.value.in.kind == "member"}.andAlso {
            o.value.in.value == "outer"} } then {
```
with
```
elseif { (o.value.kind == "member") && 
        {o.value.in.kind == "member"} && 
            {o.value.in.value == "outer"} } then {
```
It would be possible for && to check its argument and, if it's a block, apply it.

An alternative would be to use && to take a boolean and ⋀ to take a block, or vice-versa.

**Comment by apblack** [comment]
Dave Ungar tells me that we should do what Self did: everything understands `apply`, and returns `self`, except for black, which evaluate.

**Comment by KimBruce** [comment]
This seems like the same issue as the previous one with booleans.  I'm tempted to say something like all boolean expressions should be treated as blocks (including literals true and false), but that seems like an awfully slippery slope.

**Comment by kjx** [comment]
> On 4/08/2015, at 6:45am, Andrew Black <notifications@github.com> wrote:
> 
> It would be possible for && to check its argument and, if it's a block, apply it.

in a dynamic, structurally typed language, an object can be both a block and a boolean.

> Dave Ungar tells me that we should do what Self did: everything understands apply, and returns self, except for black, which evaluate.

I’m happy with that (of course)

Basically those Boolean arguments have type {apply -> Boolean} rather than Boolean.

Kim asks is it a slippery slope?    sure, if we do it everywhere! 
But we just have to be clear with ourselves this that this is the one exception in main libraries that proves the rule

J

**Comment by apblack** [comment]
On reflection, I've concluded that it is a very bad idea for booleans to have an apply method that returns their own value.  Why is this?

It's very easy (even for experience programmers) to write

```
while (condition) do { ... }
``` 

instead of 
```
while {condition} do { ... }
``` 

Right now, if you do that, you get a helpful error message that says that true does not understand apply, or something like that.  If we made true understand apply, then there would be no error — just an infinite loop.  This is not a good plan for novices.

Right now, I'm attracted to the idea of && taking _either_ a boolean argument _or_ a block (in which case, it is applied).  We can make this work if booleans understand `isTrue` or `ifTrue`or something of that ilk.  Of course, if the argument is _both_ a boolean _and_ a block, then we have to decide which takes precedence — probably it should be the boolean!

**Comment by KimBruce** [comment]
Wouldn't variant types with a match statement allow these to be programmed
relatively easily.

**Comment by kjx** [comment]
> On 28/08/2015, at 17:52pm, Kim Bruce <notifications@github.com> wrote:
> 
> Wouldn't variant types with a match statement allow these to be programmed relatively easily.

yeah, but I don’t think it’s about how hard (or otherwise) it is to program things

J

**Comment by kjx** [comment]
> On 28/08/2015, at 13:04pm, Andrew Black <notifications@github.com> wrote:
> 
> if booleans understand isTrue or ifTrueor something of that ilk. Of course, if the argument is both a boolean and a block, then we have to decide which takes precedence — probably it should be the boolean!

we could make zero-arg blocks take an ifTrue method …

J

**Comment by kjx** [comment]
spec says boolean ops can take blocks but not how that is implemented
