### ISSUE TITLE
types should support "-" 

### ISSUE THREAD

**Issue by kjx** [gracelang/language#60]
so that we can do stuff something like:

```
    method assert(value) hasType (Desired) {
        match (value)
            case { _:Desired -> countOneAssertion }
            case { _ ->  failBecause "{value} is missing methods {(mirrors.typeOf(value) - Desired).methods}" }
```

**Comment by apblack** [comment]
They do, at least in _minigrace_.   So this is a spec issue, I think.

**Comment by KimBruce** [comment]
I'm happy to support those uses.

**Comment by apblack** [comment]
It's in the spec ([Type Subtraction](https://github.com/gracelang/language/blob/master/spec.md#type-subtraction)).  So I'm closing this because there is nothing to do.
