### ISSUE TITLE
modulo: is -12 % 8 = 4 or -4?

### ISSUE THREAD

**Issue by kjx** [gracelang/language#63]
minigrace 4, Kernan -4. What should it be? 

http://research.microsoft.com/pubs/151917/divmodnote.pdf
https://en.wikipedia.org/wiki/Modulo_operation

**Comment by apblack** [comment]
The result of % is always positive.  I spent some time fixing these.  The definitive reference is, I believe, Boute, Raymond T. "The Euclidean Definition of the Functions div and mod" TOPLAS 14(2) pp127–144, 1992. http://dx.doi.org/10.1145/128861.128862


If you look at the documentation for Built-In Types, you will see, in §3.2:

```
%(other: Number) −> Number
// remainder r of self after integer division by other: 0 ≤ r < |self|; see also ÷ 

÷(other: Number) −> Number
// quotient q of self after integer division by other: self = other × q + r, where r is the result of %
```

**Comment by KimBruce** [comment]
It SHOULD always be positive, but almost all languages return a negative value if the dividend is negative, even (gasp) Haskell!

Here is one of those cases where we should decide whether to be consistent with other languages or to be correct.

I lean toward being correct, but we will need to educate students about the reality in other languages.

Kim

**Comment by kjx** [comment]
> Here is one of those cases where we should decide whether to be consistent with other languages or to be correct.


actually I think it's pretty clear we should be correct here - and we'll never have enough time to explain how every other language gets it wrong!   We need to get it right

**Comment by kjx** [comment]
Michael made this chart: 

       +7 % +10    -7 % +10    +7 % -10    -7 % -10
james        +7          +7          -7          -7
knuth        +7          +3          -3          -7
euclid       +7          +3          +7          +3
trunc        +7          -7          +7          -7

Andrew is arguing for the "euclid" definition rather than Knuth.

**Comment by KimBruce** [comment]
Of course we need to ensure that `b = (b/a).floor * a + b % a` no matter which definition we pick.  Truncate (which is not the same as floor) currently always moves us to the nearest int closer to 0, e.g. `(-5.34).truncate = -5.`
Currently 
      `print ((-5/4).truncate*4 + (-5%4))`
prints out -5, as desired.  If we change the definition of mod to give us positive numbers, then perhaps we should add a "floor" function and deprecate truncate (or perhaps keep both).

**Comment by kjx** [comment]
michael pointed out we don't agree

**Comment by kjx** [comment]
Pick **Euclid** and add `.floor` --- floor of -5.3 is -6   (round towards negative infinity)  and `ceiling`.  

Issue #69 is where these go.

**Comment by kjx** [comment]
so according to the protocol I wrote last week, this shouldn't be closed, but should be moved from "now" to "resolved, to be specd".   which I've now done.  sorry.

Andrew - Euclid may be in the spec, but floor and ceiling aren't.

**Comment by apblack** [comment]
> Andrew - Euclid may be in the spec, but floor and ceiling aren't.

They are now in the spec, and in my experimental minigrace.  They will migrate to the released minigrace when I've got the parsing of alias expressions out of its infinite loop!
