### ISSUE TITLE
What's a type (module "build order") 

### ISSUE THREAD

**Issue by apblack** [gracelang/language#64]
I find that I don't know what a type is.  For example, is this legal code?

``` grace
def empty = object {
    inherits Singleton.new
    method asString -> String {"empty"}
}

def full = Singleton.named "full"

type OptionNumber =  Number | empty | full

def block1 = { x:OptionNumber ->
    match(x)
      case {n:Number -> "Number {n}"}
      case {y:empty -> "Singleton {y}"}
      case {z:full -> "Singleton {z}"}
      case {_ -> "should not happen"}
}
```

Is `OptionNumber` a legal type?  It seems to me that `OptionNumber` is a pattern, but not a type.  But perhaps someone wiser than I could explain what a type is?

**Comment by apblack** [comment]
The reason that this is important is that I've been trying to figure out the correct order in which to generate code for a (module) object.  At first I though that **inherits** and **uses** clauses had to come first, but that's not right: we have to do **imports** first, then **inherits**, the **uses**.

What comes after that?  I thought that we should define types next — because executing a **def** might cause a type-check.  But if you say that `OptionNumber` is indeed a type, then we can have  types depend on defs, as well as defs depending on types.  

Maybe we have to do a topological sort on the defs and types?  Well, no: we also have mutually recursive types, so that dependency graph can have cycles, and so in general can't be sorted.

That leaves me thinking about doing lazy evaluation of type expressions.  So much for a simple, obvious semantics!

**Comment by kjx** [comment]
I know Michael & Tim have dealt with this. Types have to be lazy defs basically. 
which is a problem because they need.. type paramters!!

**Comment by apblack** [comment]
I can see two solutions to this problem.  

The first, and simplest, is to take the singleton types out of the language.  They really don't make sense as types.  Types are, after all intended to be a disjunction of interfaces, and their goal is to detect `NoSuchMethod` errors early  Singleton types don't do this.  I suspect that Singleton types were introduced to avoid `Maybe` types.  Well, _why_?  What's wrong with `Maybe` types?

The second, more convoluted solution, is to change the meaning of

    type OptionNumber =  Number | empty | full

so that it means, as a _type_

    type OptionNumber =  Number | typeOf empty | typeOf full

where the **typeOf** operator answers the type of its argument, which much be sufficiently manifest for that type to be manifest.  The objects `Singleton.new` and `empty`above meet this restriction.  `typeOf empty` and `typeOf full` happened to be the same, but that's OK.

As a _pattern_,optionNumber would mean the same thing as it does now: `empty` and `full` would match those specific objects only.

**Comment by apblack** [comment]
I should have added: any attempt to retain singleton types of the form illustrated in the OP requires that **def** introduce a binding that cannot be overridden.  Otherwise, the meaning of the type, once it is eventually defined, might change due to overriding.  So, if we make **def**s manifest, as advocated in #33, this would make sense.

**Comment by kjx** [comment]
What if types are **manifest, once** methods?   would that work?    #31 

Of course, they'd need parameters.  Either way they need parameters.   I can already hear @zmthy arguing for different models of type parameterisation for types and methods: types being objects parametrised by subscripting, methods being parameterised by <>

**Comment by KimBruce** [comment]
Isn’t the real issue that they be immutable.  That is, if x is immutable and the 
	type T = x | …
then the meaning of T is the immutable (singleton) object that is associated with x at the time the type is elaborated.  (I suspect I’m missing a subtlety here, but I’m sure you’ll let me know :-).  I am worried about making all defs manifest/immutable as that is not the way I’ve been using them in all my programs.  (I probably have three times as many defs as vars in my programs.)

**Comment by apblack** [comment]
> Isn’t the real issue that they be immutable
I presume that by "they" that @KimBruce means the object referred to by x in the type equation:

    type T = x | ...

I don't think that's the issue at all. Even if the object is mutable, it won't change type, so the interpretation of the equation as meaning

    type T = typeOf x | ...

would still make sense.  

I think that the issue is that the _name_ x has to be bound before the type can be elaborated, and if we expect types to be elaborated before **defs**, it doesn't make sense for a type to refer to a **def**.

I don't know what @kjx means by a manifest, once method.  A method that is guaranteed not to have any effects?  Presumably, guaranteed using our effects system!  

I realized that what I said in my [comment above](https://github.com/gracelang/language/issues/64#issuecomment-188384419) about **def**s needing to be non-overridable isn't quite true.  A **def** at the module levels already non-overriable, since object can't inherit from modules.  So retaining Singleton types is not quite as intimately coupled to #33 as I thought: we could conceivably allow a type to refer to an object named by a **def** at the module level, but not at the object level.

This is a pretty horrible rule, but it does mean that the issue that we are considering here — what is  a type — is technically independent of #33.

**Comment by kjx** [comment]
> I don't know what @kjx means by a "manifest, once method".

for now: a once #31 method where the structure of the result can be determined before the code is run

**Comment by apblack** [comment]
> for now: a once #31 method where the structure of the result can be determined before the code is run

How does this help?  The type still depends on executed code.

This issue really is about what a type is, and _not_ about module build order.  I can figure out the latter, given a reasonable definition of the former. Right now, the spec says:

>The names of singleton objects, typically declared in object declarations, may be used as types. Singleton types match only their singleton object

Having types depend on objects isn't really a problem for implementing dynamic types in the compiler: I can just make everything demand-driven.  But not having types get a meaning until runtime seems like a serious problem for a static type-checker.

Hence, my [two proposed solutions](https://github.com/gracelang/language/issues/64#issuecomment-188041537).  The simplest (and Grace is supposed to be a _simple_ language for novices, right?) is just to get rid of singleton types. I don't see what we loose — perhaps a third way of expressing something that we can already express in a couple of other ways.  The more convoluted one is to make a singleton _type_ mean the type of the singleton, and for the singleton _Pattern_ to match that specific singleton.

**Comment by kjx** [comment]
> How does this help? The type still depends on executed code.

the type depends on code that can (in principle) be execute at "manifest" type.
This is not quite compile time, but it can't be, if modules are only bound at runtime.

> get rid of singleton types.
> Types are intended to be a disjunction of interfaces

will Kim agree?   If we want a pure OO / coalegbraic language, I can see the rationale. 

> typeOf empty and typeOf full happened to be the same, but that's OK.

it's not OK, at least inasmuch as the point is types can be **checked** at _manifest time_ and patterns only at _run time_.   If they are patterns and not types, I don't see how you can test that the case handles every branch - and that's really the point of the `|` types: to be able to check case coverage properly. 

If Kim wants to give that up ---  I guess we could just delete those types wholesale.  I note Kim doesn't mention singletons or their use in match/case in his book.  

> What's wrong with Maybe types?

they're messy, generic, and mean you have to contort your program to type them statically.

do people (you amongst others) really want to write:
 
```
  var v : Maybe<Number> = empty<Number> 
  ...
  v := just<Number>(42)
 ...
 print "v={v.value}"
```

or in dynamically-typed code

```
 var v  = empty<Number> 
 ...
 v := just(42)
...
print "v={v.value}"
```

versus 

```
 var v : Number | empty = empty
...
 v := 42 
 ...
 print(v)
``` 

> and Grace is supposed to be a simple language for novices, right?) 

_Don't, don't, don't let's start_
_this is the worst part_ 

https://www.youtube.com/watch?v=pAmFTmCs3IY

**Comment by apblack** [comment]
> it's not OK, at least inasmuch as the point is types can be checked at manifest time and patterns only at run time. If they are patterns and not types, I don't see how you can test that the case handles every branch - and that's really the point of the | types: to be able to check case coverage properly.

If you insist that _types_ depend on runtime values, then I don't see how you can possibly check for exclusivity of type matches at compile time.

Your illustration that singleton types make code much better than Maybe types doesn't seem to type-check.  You need a `match(_)case(_)...` in these somewhere.  If you correct the example, then we can compare.

**Comment by kjx** [comment]
> If you insist that types depend on runtime values, then I don't see how you can possibly check for exclusivity of type matches at compile time.

singleton types - if we have them - must depend on manifest values


> Your illustration that singleton types make code much better than Maybe types doesn't seem to type check. You need a match(_)case(_)... in these somewhere. If you correct the example, then we can compare.

I didn't write a definition of `empty` --- if it had an `asString` method then that would be OK in that code I think.  I didn't know we had a type checker that checked this reliably. 

You're right, if you want to treat `v` as a `Number` then you have to do either: 

```
 print (v.value + 3) 
```

using option types, or 

```
match (v)
   case { n : Number -> print(n + 3) } 
   case { _ -> print "none" } 
```

without.   I guess the question is: which of these (if any) would people tend to write in "dynamically typed" code? 

if we had a flow sensitive type system that knew enough about manifests / ifs / etc we might even be able to check 

```
if (Number.matches(v))
   then { print v + 3) } 
   else { print "none" } 
```

or perhaps the other way around, using == to drop empty from the type?  Typed Racket can handle this sort of stuff in some cases.

**Comment by KimBruce** [comment]
> 
> You're right, if you want to treat v as a Number then you have to do either:
> 
>  print (v.value + 3) 
> using option types, or
> 
> match (v)
>    case { n : Number -> print(n + 3) } 
>    case { _ -> print "none" } 
> without. I guess the question is: which of these (if any) would people tend to write in "dynamically typed" code?
> 
> if we had a flow sensitive type system that knew enough about manifests / ifs / etc we might even be able to check
> 
> if (Number.matches(v))
>    then { print v + 3) } 
>    else { print "none" } 
> or perhaps the other way around, using == to drop empty from the type? Typed Racket can handle this sort of stuff in some cases.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/gracelang/language/issues/64#issuecomment-190431271>.
> 

For me, an important point of match was to allow type-safe discrimination and use of variants.  Thus the if (Number.matches(v)) … construct would not type-check in reasonable static typing dialects.  I particularly wanted to avoid Java’s broken 

if (v instanceof C) then {
    C vd = (C)v
    …
}

idiom.

**Comment by kjx** [comment]
note that defs can also be written to be circular:

```
  def x = someCollection(1, y, 3)
  def y = someOtherCollection(2, x, 6)
```

although as currently defined, this will get you a initialised read error, which is OK (ish) for defs.

(now try running asString on that, if you can make it!)

**Comment by kjx** [comment]
I threw something in here: not perfect at all https://github.com/gracelang/language/blob/portland-james/spec.md#combination-and-initialisation

**Comment by kjx** [comment]
The spec actually says: `Singleton(o)` is the type.. I'm not sure if it should, or if that is a problem.

**Comment by KimBruce** [comment]
Clearly we need to resolve types statically or to have static constraints (so we can statically type-check them).  We also need to be able to handle cases that might have otherwise been handled with null.  We could probably get by just with Maybe types, but they are just a special case of the more generic issue (and Maybe types are crippled because we can't give behavior to the empty object).

Thinking about it, I like the syntax
   type T = U | v.asType
where evaluating the type T would require v to be evaluated statically (and hence to be manifest) and then evaluate its asType method, which should result in an object with a match method that returns true only with something that is == to the current value of v.  I'd be fine with restricting further so that v must be manifest and immutable.  I would even consider require adding an annotation "is manifest" to make clear our intentions.

**Comment by kjx** [comment]
does that make `asType` another default method?   Can it be overridden?  if not, it's just a syntatic variation for `Singleton(o)` as in the spec, (which also has a `manifest` annotation already)

**Comment by apblack** [comment]
I don't like Kim's suggestion.  Making `asType` a method on an object circumvents the intention of mirrors, which is that all reflection has to go through them.  And, as Kim says, `v` would have to be declared in a special way to ensure that it can be manufactured at compile-time.

It makes more sense to me to have a language builtin **typeOf** that can be applied to any object, and returns whatever type can be statically inferred for it.   So, yes, adding more type annotations might change what **typeOf** returns.   

As far as I can see, types should not depend on values.   `3` and `4` always have the same type, because they always have the same set of methods.     

In hindsight, it was a mistake to use a single contract (`match(_)case(_)`) to discriminate on both types and values.   Is it too late to revisit that?

**Comment by kjx** [comment]
> I don't like Kim's suggestion. Making asType a method on an object circumvents the intention of mirrors

I don't either - but this is just syntax, and unrelated syntax at that. 

> It makes more sense to me to have a language builtin typeOf 

sure - though this unrelated to the question of what a type actually _is)
I think I put that in as #92 when culling the list of issues out of the spec into here.
I quite like `typeOf` but on reflection would prefer `declaredType` or something like that.

> In hindsight, it was a mistake to use a single construct match(_)case(_) to discriminate on both types and values. Is it too late to revisit that?

I really don't see this, and (hopefully) yes, although really no.  Or rather: I hope you're happy to release the current version of the spec with match()case() in, as it's been around for years...

**Comment by KimBruce** [comment]
In retrospect, I’m less happy with the typeOf as well.  I do like our singleton notation and would prefer to go that way.

I’m happy with the single match-case.  I understand you don’t like type-case part of match, but I’d like to keep it and, if so, keep a uniform notation for it.

The whole point of singleton types is to create essentially a branded type with only a singleton element.  Yes, it must be manifest, but I don’t see that as a major problem.

Kim

**Comment by apblack** [comment]
My point in suggesting __typeOf__ was indeed to give a _meaning_ to Singleton, as described in my comment [above](https://github.com/gracelang/language/issues/64#issuecomment-188041537).
It was also to re-open the issue of type inference, which we need anyway to make type matching a true/false operation (as opposed to a true/false/maybe operation).

**Comment by KimBruce** [comment]
You'll need to explain what you mean by type inference, as ML-style type inference is pretty hopeless for a language like this (Scala's attempt to do this is one of the reasons I dislike it as it is pretty unpredictable whether or not it will work -- even in cases where it is pretty easy for humans to deduce types).  Principle types disappear al

If you are considering a very weak sort of local type inference, there may be some hope, but I've argued in the past that type inference should be considered more a part of an IDE than part of a languages run-time.

**Comment by apblack** [comment]
> You'll need to explain what you mean by type inference, as ML-style type inference is pretty hopeless for a language like this (Scala's attempt to do this is one of the reasons I dislike it as it is pretty unpredictable whether or not it will work -- even in cases where it is pretty easy for humans to deduce types). Principle types disappear al

Well, I really wasn’t.  That is, I got out of the types game many years ago, and have deliberately left this to you and James to sort out.  But the “Jon Boyland Lacuna” says to me that if you want a dynamic type test to give you sound typing inside a “case”, then you need to come up with a plan for type inference.  Singleton types say the same thing.

To be explicit, consider the case where the subject of a match was created without any type annotations, and there is no type inference.  The pattern in a case branch can check for the presence of methods (a “single level” type check), but not the argument and return types of those methods.   If you want the pattern to be equivalent to a dynamic type check, then its essential that we can do this check.

I can see several alternatives:

	(1) Require that in any program with a match(_)case(_), any value that could flow into the match be fully annotated with type information.
	(2) Inside a case that _might_ match, wrap the subject inside another object that _does_match, and guard results of the wrapper with another “single level” type check, and then wrap the result … and so on, recursively.  Getting this right is quite complicated, because the arguments of arguments need to be guarded too …
	(3) Change the semantics of the dynamic type check in a match(_)case(_) to explicitly be single level, which means that match(_)case(_) will not, and should not be expected to, guarantee type safety.
	(4) Abandon the type-case aspects of match case.
	(5) Do type inference, so that objects without explicit type annotations get inferred annotations.  As you say, these may not be as strong as a programmer would add — in the worst case, the annotation might be `Unknown`.   If such an annotated value flows into a `match(_)case(_)`, and the annotations are insufficient to make a true or false determination in a case, then we would raise soem sort of dynamic error.

(1) makes nonsense of the idea of gradual typing.  (2) sounds very complicated; the “blame” industry has worked a lot of this out, but in the context of functional languages, where I believe that things are simpler.  Has this been done for a stateful O-O language?  (3) You have explicitly said you don’t want, (4) James has rejected ... which leaves us with (5).  Maybe you can think of other options.

> If you are considering a very weak sort of local type inference, there may be some hope, but I've argued in the past that type inference should be considered more a part of an IDE than part of a languages run-time.

I don’t see how an IDE could help with this problem.  I do agree that having an IDE that lets the programmer ask about the inferred type of an expression would be useful — in fact, I was trying to talk a student into doing this on Thursday (but I was unsuccessful).   But `match(_)case(_)` explicitly requires that the full type of the subject is available at runtime; how could an IDE help?

**Comment by apblack** [comment]
In teleconference on 5 April, we agreed to adopt my "proposed solution" — which I intended to be the second [proposed solution above](https://github.com/gracelang/language/issues/64#issuecomment-188041537).

**Comment by apblack** [comment]
I put some words in the Spec.  I found it necessary to include this phrase in the "Combination and Initialization" section.

> Types cannot depend on runtime values; if they depend on the type of a constant (because the constant is treated as a [Singleton type](Singleton Types), then that constant, if overriden in a subclass, can only be overriden by a new object with the same type.

**Comment by KimBruce** [comment]
I think I missed this part of our discussion today.  I believe the only reasonable solution is to only consider the values at the time the type definition is elaborated.  I.e., if empty and full are as given in the first posting above, then defining the type "OptionNumber =  Number | empty | full" should use those values, even if empty and full are overridden later.  Obviously overriding them in this case would be pretty stupid, but the semantics should be specified.

I believe we should require values in types to be immutable (and manifest) as well.

**Comment by apblack** [comment]
Now that `Singleton` does not introduce a type, it's pretty simple to say what a type is (I think):

 * A type literal denotes a type
 * A type expression, using one of the type operators `|`, `&`, `+`, and `-` and with types as its arguments, denotes a type
 * A name defined in a type declaration, denotes a type.  The hrs of the type declaration must denote a type.
