### ISSUE TITLE
James model semantics for traits inheritance combination 

### ISSUE THREAD

**Issue by kjx** [gracelang/language#67]
https://github.com/kjx/combinators has grace code that models traits. 
It's testable but ugly; Tim's semantics in Graceless are clearly more graceful but harder to follow. 

To run the code, you need  newcol.grace, that particular combinators.grace, inheritator.grace, and inheritator-test.grace. On a very recent Kernan, run inheritator-test.grace

**Comment by kjx** [comment]
### main inheritance semantics  
the same for classes, traits, or objects (phew)

- traits override classes (modulo abstract)
- trait composition is symmetric
- local defs override traits and classes

```
   method structure  {
     def superStructure = nc.list ([ ])
     for (supers) do { i -> superStructure.addAll(i.structure) }     
     def traitStructure = nc.list ([ ])
     for (traits) do { i -> traitStructure.addAll(i.structure) }
     def supersAndTraits = override(superStructure) with(traitStructure) 
     def finalStructure = override(supersAndTraits) with(locals) 
     finalStructure
   }
```

most of the work is done by the override( low ) with ( high ) method:
This basically deletes things from the list of "low" priority declarations, resulting in "lows" , while keeping high priority declarations into the list of "highs", while handling abstract methods etc.  Then we check overriding and final. 

```
   method override(low) with(high) {
     var lows := nc.seq(low)  //avoid side fx on low
     var highs := nc.seq ([ ])
     for (high) do { d ->
         if (!d.isaAbstract) 
           then { //concrete
                  lows := lows.filter { l -> ! ( l <-!-> d ) }
                  highs := highs ++ ([ d ])
           } else { //abstract, add only if nothing there
             if (! declaration(d) conflictsWith(low)) 
                    then { highs := highs ++ ([ d ]) }
         }
         if ((d.isaOverrides) && 
             (! declaration(d) conflictsWith(low)))
           then {Exception.raise "{d} in {name} does't override anything"} 
     }

     for (low) do { l -> 
         if (l.isaFinal && ! nc.seq(lows).contains(l))
           then {Exception.raise "{d} in {name} is FINAL but overridden"} 
     }
     nc.seq(lows ++ highs)
   }

```

This hopefully enforces: 
- overrides methods must override
- abstract methods do not override 
- final methods must not be overridden. 
Any remaining trait conflicts are also errors. 

This code computes the **aliases** by adding in xtra declarations, and making them confidential
```
     method structure -> nc.Sequence<String> {
        def bs = base.structure
        def xtras = nc.list ([ ])
        for (bs) do { each -> 
          if (aliases.containsKey(each.name)) 
            then { xtras.add( each.maybeRename( aliases )
                                  .withAnnotation( "confidential" ) ) }
        }
        bs ++ xtras
     }
```

while exclusions are simpler 

```
     method structure -> nc.Sequence<String> {
        base.structure.filter { each -> ! ( excls.contains(each.name)) }
     }
```

The model also calculates the initialisation code, but that's mostly uninteresting.    And yes, I know this could have been done better with much smaller combinators, but this is as far as I got!

**Comment by kjx** [comment]
Nasty, nasty questions:
 - what if two traits are combined, one with a "confidential" method and one without? 
 - can a trait ever have an overrides method if it doesn't override anything in a super-trait (but with the intention that it must override something in any class to which it is mixed in)
 - what if a public abstract method tries to override a confidential method?

at this point, I given up for today!

**Comment by kjx** [comment]
I extended inheritator so that it can generates exhaustive tests - and updated the code above to match the current version in the github. Now you can look at LOTS of examples and see what the resolution is.

This generated version doesn't have excludes or aliases but it could.

[GENERATED.txt](https://github.com/gracelang/language/files/142654/GENERATED.txt)

**Comment by apblack** [comment]
What does `<-!->` mean?  What's "inheritator"?

I like less and less the idea that annotations are on _names_ rather than _methods_. In part this is because I can't see how to implement it simply.

I don't see a problem with overriding a confidential method with a public one — or the other way around.  After all, a trait combination could exclude the confidential method, creating a new trait, which could then be used in a class that adds back the previously confidential, now excluded, method.

If two traits are combined, and they both have methods with the same name, then that is a conflict, regardless of their visibility.  If the programmer doesn't like that, they can exclude one or the other (or both).

**Comment by kjx** [comment]
> What does <-!-> mean?

two declarations conflict (have the same name, but perhaps different bodies etc)

>  What's "inheritator"?

the name of the model? 

> I like less and less the idea that annotations are on names rather than methods.

my conceptual model didn't reify "methods" or at least didn't separate methods from their names.
perhaps this is no longer viable. I dunno. 

> I don't see a problem with overriding a confidential method with a public one 

neither do I: there isn't one

> or the other way around. 

that implies we really would give up any links between subtyping and subclassing / inheritance.
(although I guess you could have different rules for classes and traits...).
Kim: are you sure you wants to go that far? 

Then again, I'm still worried the "excludes" (and perhaps the "alias") semantics prevent modular type checking anyway. Tho' I guess we could argue Kim can run a much tighter dialect that would reimpose all those restrictions. 

> If two traits are combined, and they both have methods with the same name, then that is a conflict,  

If we really are moving that far away from static checks in the core, I find it really hard to understand why trait conflict should be a hard, eager, early error,  while all these other things are detected softly, lazily, and late. 


(hmm - thought I drafted this, dunno where my answer went)

**Comment by kjx** [comment]
Coming from #47 and #68 - use clauses cannot use explicit or implicit "self"   (also annotations & types) 

On reflection, I'm not actually sure *why* - if our inheritance semantics actually mean that we have to re-check/re-compile all the superclasses in the context of the subclassses anyway, if inheritance is completely unrelated to subtyping, they we can make the semantics in turns only of concrete objects
so i.e. only when self is bound.

Note that this would give us virtual *classes* and virtual *types within classes*    but types would still be invariant within types. 

(andrew read classes and traits for classes) 
(although Jonathan Aldrich sent me an example years ago a still have to thing more about)

I dunno how much the semantics of exclude affect this, they must be bit, but if there are no constraints on the types it probably doesn't matter very much.

**Comment by KimBruce** [comment]
This just occurred to me.  All things defined at the top level use an implicit self.

def x is public = 1

    class sup(n,k) {
       ...
    }

    class sub(n) {
        inherits sub(n,x)
       ...
    }

x is really self.x.  Surely we don't want to ban its use as a parameter!

**Comment by apblack** [comment]
> All things defined at the top level use an implicit self.
> 
> def x is public = 1
> 
> class sup(n,k) {
>    ...
> }
> 
> class sub(n) {
>     inherits sub(n,x)
>    ...
> }
> 
> x is really self.x. Surely we don't want to ban its use as a parameter!

No, indeed not.  

The point is that inside `class sub`, that `x` means `outer.x`.  If `x` were to be redefined inside `sub`, then `x` would mean `self.x`, and would indeed be illegal under my proposal).

`n` is a direct reference to the parameter of the factory method, so it�s OK too.

**Comment by KimBruce** [comment]
Let’s discuss this tomorrow as either the spec is not right or I’m not understanding it.

Kim

**Comment by kjx** [comment]
This is about #47 definition of manifest. The wording in the spec allows calls on `x` because expressions that resolve to manifest declarations in the module or dialect are manifest (but pretty much nothing else is :-)

I will add another example to #47 when I get time

**Comment by kjx** [comment]
I'm working on an improvised, revised model at https://github.com/kjx/inheritator2 
It's not done yet.
