### ISSUE TITLE
Multiple definitions of a method in an object

### ISSUE THREAD

**Issue by apblack** [gracelang/language#7]
Should we allow multiple definitions of a method in an object?  In early versions of Grace this was allowed, to permit the "inheritance by extension" semantics.  The last definition won.

In _minigrace_ it used to be allowed, with the first definition winning (I think).  It is currently detected as an error by _minigrace_ — I implemented this check in Fall 2014.

But I don't believe that we ever made a formal decision to make such objects illegal.  Should we?

If we don't make them illegal, then we have to give them semantics.  The three obvious options are
* ambiguity error.
* the first definition wins
* the last definition wins

There are also more complicated options, I'm sure.

**Comment by KimBruce** [comment]
Ambiguity error!  What is the compelling reason for this -- we haven't needed them to this point!?  I especially hate the possibility of finding one definition and not realizing that just off the screen is another definition that replaces it.  Not the thing to win the hearts of novices.

**Comment by kjx** [comment]
> On 4/08/2015, at 6:50am, Andrew Black <notifications@github.com> wrote:
> 
> But I don't believe that we ever made a formal decision to make such objects illegal. Should we?

given the way our design is going - yes.

J
