### ISSUE TITLE
Overriding an inherited type

### ISSUE THREAD

**Issue by apblack** [gracelang/language#8]
Is it possible to override an inherited **type**?
* Never
* Only if the _overriding_ types is more restrictive
* Only if the _overridden_ type is more restrictive
* Only if the definitions are _identical_

**Comment by KimBruce** [comment]
Never.  Type definitions in objects should only be considered as scoping and visibility.  Static typing becomes incredibly tricky (think beta).  I'd like to eventually allow SelfType as a keyword type, which will give some flexibility (but will still require care).
