### ISSUE TITLE
Interface of singleton(o) types

### ISSUE THREAD

**Issue by kjx** [gracelang/language#81]
What’s the interface of singleton types (I carefully didn’t say).

see: 

https://github.com/gracelang/language/blob/portland-james/spec.md#singleton-types

https://github.com/gracelang/language/blob/portland-james/spec.md#self-matching-objects

**Comment by apblack** [comment]
I think that I said: it's the interface of the singleton.

**Comment by apblack** [comment]
With issue #100 resolved by taking Singleton types out of the spec, this issue was resolved by ... taking singleton types out of the spec (in commit 7bae9d22d).
