### ISSUE TITLE
Subtyping vs Subclassing

### ISSUE THREAD

**Issue by kjx** [gracelang/language#82]
Do we really want to say this?  If not then what?  More to the point - do we care?

> If a class or object B inherits from another class A, then B’s type
> should conform to A’s type. If A and B are parameterized classes, then
> similar instantiatons of their types should conform.

https://github.com/gracelang/language/blob/portland-james/spec.md#type-conformance

**Comment by kjx** [comment]
See discussion on #67, #72.  These issues are here to make sure Kim knows what he's signed up to!

**Comment by KimBruce** [comment]
If we include exclude, then we are no longer tying together subtyping and subclasses.  This is fine with me (in terms of public interfaces).  As I have expressed many times, I'm not happy about breaking existing code that references the "excluded" code.  Our new semantics with replacing the "excluded" method with a confidential "requested" method at least raises an alarm (hopefully with a good error message).

Not surprisingly, in a statically typed dialect, I will require all "requested" methods to be gone by the time we create a new object, so we will be able to guarantee method not found errors won't appear.  I will put enough restrictions on that we can still do modular type-checking.  I'm mainly at this point trying to ensure you guys don't put something in I can't work around!

**Comment by kjx** [comment]
> If we include exclude, then we are no longer tying together subtyping and subclasses. 

or if we allow subclasses to arbitrarily change type declarations (which we do) 

> Our new semantics with replacing the "excluded" method with a confidential "requested" method at least raises an alarm (hopefully with a good error message).

yes. 

> I will put enough restrictions on that we can still do modular type-checking. I'm mainly at this point trying to ensure you guys don't put something in I can't work around!

which is why the manifest rules are important (although I guess they could be dialectual... hmm don't want to think about that right now)

**Comment by KimBruce** [comment]
They are indeed different
