### ISSUE TITLE
Semantics of Equality

### ISSUE THREAD

**Issue by kjx** [gracelang/language#91]
What should equals mean?  What should the default implementation?

I'd always kept half a candle for EGAL, but it has problems - if it cannot be overridden, it stops abstraction. 

I think Pyret's equality definition is complex, but useful as a guide to possibilities, notably their equal-always is egal. 

https://www.pyret.org/docs/latest/equality.html

I like their names though:
 *  **always equal**: if a == b then a is always equal to be
 * **equal now**: if two objects are "currently" equal but values may change later
Plus they have lots more equalities. 

They write =~ for "equal now" which I'm not sure I like (too close to ~= which seems to me like not equal) 
but it does look like a "weaker" equality than ==. 

If we were to adopt this scheme, the main change would be that mutable collections would not override ==, but replace it with =~

J

**Comment by kjx** [comment]
there's also the issue of what type equals should be:

```
 method ===(other : Self) { .. }
```

has superficial appeal, until suddenly I realised that most calls to === would then crash with a type error. 
oops.  pity. 

we could complexify the language by doing something like:
```
method ==( other  : type { } )  { 
  match (other) 
    case { otherSelf : Self -> self === otherSelf }
    case { _ -> false } 
```

where `==` is relaxed in the types it takes, but `===` is strict.  Programmers would only define ===.

**Comment by KimBruce** [comment]
Any time you are going to use a Self type in a covariant position (e.g. parameter) then you really need exact types.  I don't think we want to use those now, so I would advocate for an == that takes any object as a parameter and perhaps a generic one eq<T>: T -> Bool.

I do like pyret's three different equality operation.  == now (for mutable objects) and == always (e.g. for immutables) are pretty compelling.  The third might be a bit too confusing.

**Comment by kjx** [comment]
Argh!  this comment - https://github.com/gracelang/language/issues/49#issuecomment-205724914 - should have been in here.
