### ISSUE TITLE
Type enquiries 

### ISSUE THREAD

**Issue by kjx** [gracelang/language#92]
Do we need more support for enquiring about static types (`decltype` ?) and dynamic type (`dyntype` ?). Note that neither of these can be a method request.  How does that work with reflection (_dyntype must be reflexive_)

do we want to be able to write `declaredType( expr )`

**Comment by kjx** [comment]
Andrew proposes `typeOf(e)` https://github.com/gracelang/language/issues/64#issuecomment-199646912 which James quite likes

**Comment by apblack** [comment]
Getting the dynamics type should be a request on the object's mirror, shouldn't it?

**Comment by kjx** [comment]
yes  it should

**Comment by apblack** [comment]
And `typeOf` should be **typeOf**, a new language keyword, I think.  The point is that it's not a method executed at runtime, but a language construct that is evaluated _before_ execution time.

An alternative is **like**, which I think is what Eiffel uses.  So one could say **like** `self` instead of `Self`.

**Comment by kjx** [comment]
Yeah, and I remember *like* was another bad thing about Eiffel, precisely because of "like Current" (aka like self). Along with their *undefine* clause... 

I guess it's not too bad if we require the argument of typeOf( x ) to be manifest - given the current definition of manifest.  In fact if it's to yield a usable type, it needs to be manifest, doesn't it?

So typeOf( self ) wouldn't be manifest.  But I guess it means the same as *Self*.   

OK now I'm confused, and we should make sure the types people chime in before we decide.

**Comment by apblack** [comment]
I though that the whole idea of providing a way of getting at the static type was to use it in type contexts, which requires that the result of **typeOf** _is_ manifest.  The argument need not be manifest, but it's _shape_ needs to be at some level.  For example

```
def aWombat:Wombat = ...
def aKoala:Koala = ...
def aMarsupial = if (random.choice) then { aWombat } else { aKoala }
typeOf aMarsupial ??
```
In this snippet, `typeOf aMarsupial` would be `aKoala | aWombat` — that's what we know statically.
Or, maybe it's `Object`, because w don't do type inference.  The dynamic type would, of course, be `Koala` or `Wombat`.

**Comment by KimBruce** [comment]
I'm nervous about this unless it is just done with mirrors.  I'm not even sure of what typeOf should mean.  Is it the inferred type (what the type-checker would derive -- declType above)?  Is it a run-time type (Dyntype)?  If so, is it guaranteed to be the most accurate type or just some type?  What if we can't determine its type at run-time (or does every object know its type when it is created and modified)?

If it is static (e.g. decltype above) but we are not in a statically typed dialect, then can we always derive a unique minimum type?  What about {x -> x}?  It has type {apply: b -> b} for any b (including unknown).  None of those are the minimum type.  I think there is a good reason we don't see this in languages.

**Comment by apblack** [comment]
We have type enquiries on objects using reflection — that's @kjx's `dyntype`.  They will typically have a bunch of `Unknown`s in them, but they will be accurate to one level: method names, but not necessarily their argument and results types.

I think that we can also have manifest type enquiries on _expressions_ (**typeof**)— but it would be hard to specify what comes out of such enquires without also specifying what the type inferring part of the type checker does.  So I wonder how much use they will be.

I think that we should probably not add **typeof** until we have some experience with the type checker.

**Comment by kjx** [comment]
I'm back to preferring **declaredType** rather than **typeof**.  
But I fear they won't generally do what people want.

**Comment by apblack** [comment]
We agreed (by email during the last week of January 2017) that we would not add static type enquires at this time.  The reflection interface (yet to be defined) will probably allow dynamic type enquiries.
