### ISSUE TITLE
lineup iterable literals vs overriding on arity

### ISSUE THREAD

**Issue by kjx** [gracelang/language#94]
Comments from the mailing list below

**Comment by kjx** [comment]
(from Michael) 

With the recent introduction of [ ... ] iterables, there are now two
different kinds of method application brackets (in effect).¹

When *declaring* a method, you only use (), and you specify the other
kind using a type annotation.

When *calling* a method, both kinds are in use. The difference between
the two is that one kind is used for a method that takes arbitrarily
many arguments, while the other is used for methods that accept a
fixed number. The caller of the method must know this fact about the
method implementation, even though in the concrete case they are
always passing a fixed number of arguments.

If you use the wrong kind of bracket, you will get a type error.

Is it necessary to impose this complexity onto the novice user?
-Michael

¹ Of course, you *can* use [] outside of method calls, as in `def x =
[1,2,3]`, but it doesn't seem very useful. At one point I thought I
saw that [] were not intended for end-user use at all, but only for
internals of library implementation, but they seem to be appearing in
user-facing interfaces such as `list [1,2,3]` now. It always seemed
odd that something nobody was going to use was the shortest object to
create, so that seems like a logical development. In this message I'm
considering their use as direct arguments to a method call only, where
a variably-sized list of values is passed to the method.

For clarity, an example of both styles of call is:
```
   list ( 1, 2, 3 )
   list [ 1, 2, 3 ]
```

And the declaration:
```
   method list(x, y, z) { ... }
   method list(items : Iterable<Number>) { ... }
```

**Comment by kjx** [comment]
this is not a setup - but I can see Michael's point.

thinking about this (again) - it is a bit odd that (given overriding with arity) all of 

l```
ist
list (1)
list (1, 2)
list (1, 2, 3)
list (1, 2, 3, 4)
list (1, 2, 3, 4, 5)

```
are legal, and at least able to be defined as easily as 

```
if (_) then (_) 
if (_) then (_) else ()
if (_) then (_) elseif () then () else ()
if (_) then (_) elseif () then () elseif () then () else ()

```
if we get rid of [] brackets in BOTH indexing AND "iterables" then we could use [ ] for generics with *no* parsing issues whatsoever.

for the time being, minigrace could just special case the parser so writing list() or seq() does what [] does now.

Yes, people passing sequences would have to write:

```
myWindow.addWidgets (seq(
  title "Launch",
  text "Good Morning Mrs President", 
  button "OK" action { missiles.launch },
  button "Cancel" action { missiles.abort }
)) 
```

rather than 

```
myWindow.addWidgets [
  title "Launch",
  text "Good Morning Mrs President", 
  button "OK" action { missiles.launch },
  button "Cancel" action { missiles.abort }
]

```
but getting rid of BOTH indexing and "lineups" would really simplify this part of the language.
I have been sceptical of taking on overriding on arity but this would help convince me.

But going one step further: how much is it worse than writing e.g. 

```
list
list (1) 
list (1) and (2)
list (1) and (2) and (3) 
list (1) and (2) and (3) and (4)
list (1) and (2) and (3) and (5) and (5) 
```

or 

```
myWindow.addWidgets 
 (list (title "Launch") 
  and (text "Good Morning Mrs President") 
  and (button "OK" action { missiles.launch}) 
  and (button "Cancel" action { missiles.abort }) )
```


HMM: I can see the first one being clumsy, but the second looks... surprisingly fine.



Andrew might ask - what happens to "`list.empty`" - answer  - we just write "list".
what happens to "`list.withAll`"  - we just write listWithAll  or `listFromAll` or `something.asList`

**Comment by kjx** [comment]
Or we could just change the definition syntax: 

```
   method list(x, y, z) { ... }
   method list [items : Number] { ... }
````

but on the whole, I like removing 'lineups' and just overriding the constructors much better!

**Comment by KimBruce** [comment]
I personally don't mind putting in list(seq(1,3,5)) rather than list[1,3,5].  I believe that seq could then be the only thing that takes a variable number of parameters (essentially overloaded by arty for lots of rarities!).  Dropping the use of [] for everything else would then allow us to use square brackets for type parameters and get rid of the rules about when spaces are and are not allowed around < and >.

**Comment by kjx** [comment]
> I personally don't mind putting in list(seq(1,3,5)) rather than list[1,3,5]
> I believe that seq could then be the only thing that takes a variable number of parameters

that's another option, basically a different API design still based on arity overloading

> Dropping the use of [] for everything else would then allow us to use square brackets for type 
> parameters and get rid of the rules about when spaces are and are not allowed around < and >

yes that's right.
